chakra-ui/chakra-ui-docs

- pages/docs/features/style-props.mdx
Just added **shadow** prop to the table showing a list of style props. 
No
> docs(style-props): add boxShadow shorthand

- pages/docs/features/color-mode.mdx
Move docs adjusted here https://github.com/chakra-ui/chakra-ui/pull/4989
> feat(docs): add description how color mode behaves

- pages/docs/comparison.mdx
Comparison Docs addition to "How is Chakra different from Material UI?" section.
No docs describing the difference between Chakra UI & Material UI
Notes comparing the two frameworks.
No
> docs: Chakra UI vs Material UI comparison addition

- configs/search-meta.json
- layouts/index.tsx
- layouts/mdx.tsx
- pages/faq.mdx
- pages/faq.tsx
- src/components/mobile-nav.tsx
- src/components/sidebar/sidebar.tsx
Closes #12 
Adds a FAQ Page to the docs website.
The new FAQ Page uses mdx to provide content.
No
I decided to use mdx in the end instead of the json file as i did in #30 as it enables better ways to structure the answer (e.g code examples) and means less changes for the search gen script.
> Add Faq Page

- src/components/algolia-search.tsx
Synchronizing with the main [charkra-ui](https://github.com/chakra-ui/chakra-ui) repo.
Missing PRs from main repo.
Moved PR #5019 from main repo to new repo.
> docs: sync changes with main repo

- pages/docs/theming/advanced.mdx
Closes # 
I noticed that the import was missing when trying to follow the code instructions :). 
**No**
> docs(advanced-theming): add import for useStyleConfig

- .github/workflows/daily.yml
Closes #  
Add an action in `daily.yml` to generate showcase data automatically
No
> chore: add an action to generate showcase data

- i18n/ui.json
- src/components/mobile-nav.tsx
Added a Showcase link in Mobile Nav.
No
> docs(nav): added showcase button in mobile nav

- configs/resources.json
Closes #11 
This PR updates the `resources.json` file content as per latest resources for getting insights about Chakra UI.
Typically, now the latest change would contain (with apt data attributes like heading, description, tags etc.):
- All the blogs, talks and videos listed in the `#showcase` discord channel till now
- Design Vs. Dev Challenge Video Resources
- Component of the Week Resources
No, there is no breaking change.
For future prospects, I have a couple of suggestions over maintaining showcase/resource etc. community-driven content for the docs. Would love to know your views upon it:
- The data for this page (say resources) is being taken from `resources.json`. In a typical JSON file, adding `comments` is not permitted. 
- There are a lot of content creators, bloggers and …
> Update Resources Page data

- configs/docs-sidebar.json
- pages/docs/hooks/use-const.mdx
Closes # 
Add a page for the `useConst` hook.
No.
N/A
> docs(hooks): add use-const page

- pages/docs/overlay/popover.mdx
- yarn.lock
Closes #57 
Add new popover anchor feature to docs
Popover docs with no `PopoverAnchor` feature
Introduce how `PopoverAnchor` works
no
Run once `yarn`
> docs(popover): add new popover anchor feature

- pages/docs/feedback/toast.mdx
- yarn.lock
Closes #56 
Add an example to demo a new prop `containerStyle` of toast
No demo about `containerStyle`
Add an example to demo a new prop `containerStyle` of toast since it's a new feature built in [chakra-ui/chakra-ui#4922](https://github.com/chakra-ui/chakra-ui/pull/4922), 
No
> docs(toast): add containerStyle to toast doc

- configs/resources.json
> Adding the first Chakra Shorts video to the resources page.
> Currently the Chakra Shorts video isn't present on the resources page.
> Users can now watch the first Chakra Shorts video from the resources page.
> No
> Adding first Chakra Shorts video to resources page

- configs/resources.json
> Changing the author of the first Chakra Shorts video to Andrej (me) instead of ChakraUI.
> Currently it's set as ChakraUI, just updated the author.
> Renaming of author in the resources page.
No.
> Changing author of Chakra Short to Andrej Acevski instead of ChakraUI

- src/components/props-table.tsx
This PR adds detailed types for theme dependent props.
> feat: Show detailed types for size, variant and colorScheme from theme

- package.json
- pages/changelog/content.mdx
New release updates. Bumping the version of `@chakra-ui/react` and sibling dependencies. Updating changelog as well.
No
> docs(chore): updates for new release

- configs/guides-sidebar.json
- pages/guides/integrations/with-storybook.mdx
Add documentation for `@chakra-ui/storybook-addon`.
No
> docs: add storybook-addon guide

- pages/docs/hooks/use-breakpoint-value.mdx
See this discussion: https://github.com/chakra-ui/chakra-ui/issues/3018#issuecomment-1003737292
> Add notes in `Usage` section

- package.json
- pages/changelog/content.mdx
- yarn.lock
Add changelog and update @chakra-ui/* packages.
Uses v1.7.4
Uses v1.7.5
No
> docs: update changelog for v1.7.5

- pages/changelog/content.mdx
We no longer use legends to describe features or fixes in the changelog, hence the need to remove all legends
No legends in the changelog
No
> docs: removed legends

- configs/docs-sidebar.json
- configs/search-meta.json
- pages/docs/features/semantic-tokens.mdx
- pages/docs/features/style-props.mdx
Initial docs draft for unreleased feature **Semantic Tokens**. 
This feature will be released with `@chakra-ui/react@1.8.x`.
> docs: add semantic tokens docs

- configs/guides-sidebar.json
- configs/search-meta.json
- pages/guides/recipes/floating-labels.mdx
- src/components/mdx-components/mdx-components.tsx
Closes #212 
Adding a recipe for adding floating labels to Chakra UI. This should give users all the tools needed to implement this or any other style.
N/A
N/A
No
See the full code example here: https://codesandbox.io/s/optimistic-shockley-g0uls?file=/src/index.tsx
> docs(recipes): Adding floating labels recipe

- package.json
- pages/changelog/content.mdx
- yarn.lock
> chore: bump chakra to v1.8.1 and update changelog

- src/components/sidebar/sidebar-category.tsx
Adjust sidebar title to Chakra color for better readability and section distinction.
No
> docs: Adjust sidebar title color to Chakra color for better readability

- configs/showcase.json
- src/components/showcase/showcase-section.tsx
Closes #279 
Replaced the choc ui link with the new url
No
> docs: replace choc-ui link

- pages/docs/form/input.mdx
Docs for the following PR: https://github.com/chakra-ui/chakra-ui/pull/5507
Add docs for the new htmlSize prop with an example on how to use it.
There is no htmlSize prop, thus no docs.
There is docs for the new prop.
No
Should only be merged when the PR gets released, to not confuse users.
> docs: add docs for the new htmlSize prop

- configs/sandpack-contents/homepage/files.ts
- package.json
- pages/index.tsx
- src/components/sandpack-embed/index.tsx
- yarn.lock
Hey @nikolovlazar, I noticed that the Sandpack example on the homepage is currently not working properly (maybe it's our fault, as we updated the template files recently). So, here are the changes necessary to fix the file mismatch (which was causing an empty sandbox) and a set of other measures to improve the Sandpack behavior.
- No valid sandbox;
- No light theme;
List of changes:
- Updated Sandpack version;
- Fixed the file path passed to Sandpack;
- Added dark/light mode;
- Removed all unnecessaries dependencies from Sandpack config;
- (Optional) Added a new component around the example to center the card;
| Light | Dark |
| - | - |
| ![Screenshot 2022-02-07 at 16 28 50](https://user-images.githubusercontent.com/4838076/152829828-bc530f48-c980-45eb-ab30-0112ec525cd8.png) | …
> fix(sandpack): set of measures to fix and improve the experience

- pages/docs/theming/component-style.mdx
Closes -> no Issue atm
Adds informations of the current typing for Component Styles as well as informations about available parts in multipart components.
At the moment there are no informations about these two topics.
Improved Docs with more background informations about theming and 'low level' type support for the component styles.
No
Good for beginners I guess, helped me a lot with my first steps last year. :)
> docs: add component style types in examples

- pages/docs/features/style-props.mdx
Closes #290 
Typo in comment at the margin example.
Wrong amount of px in comment.
Right amount of px in comment.
No
> docs: fix typo in margin example

- pages/docs/form/form-control.mdx
- pages/docs/form/slider.mdx
this is a minor grammar fix :
export -> exports in two pages (Slider and Form Control)
No
> docs: minor grammar correction

- pages/docs/theming/component-style.mdx
> Updated a small typo in theming/component-style screen
> docs: fix a small typo in theming/component-style screen

- pages/guides/recipes/using-fonts.mdx
Added hints for defining font-family fallbacks.
No hints for font-family fallbacks.
Short hints for font-family fallbacks.
No
> docs: add hints for font fallbacks

- pages/docs/features/css-variables.mdx
- pages/docs/features/semantic-tokens.mdx
Fixed typos
typos
no typos
No
Searched also for other 'stc' in the whole project.
> docs: fix typos

- package.json
- pages/changelog/content.mdx
- yarn.lock
> chore: bump chakra to 1.8.6

- configs/guides-sidebar.json
- configs/search-meta.json
- pages/docs/form/editable.mdx
- pages/guides/recipes/atlaskit-editable.mdx
I've added a new example with a custom input, custom controls and a UI.
No
> docs(examples): Add custom input and controls examples

- pages/docs/features/color-mode.mdx
Closes # 
Update Gatsby broken link in color mode features
Delete broken link and replace it with active link
Update link
No
> docs: update gatsby broken link in color mode page

- package.json
There are no tests and no test runner as a dependency
If you try to run `yarn test` you will face an error because there is no jest installed
Removing unnecessary script
No
> [Scripts] Removing test script

- pages/docs/features/style-props.mdx
Adding `gap`, `row-gap` and `column-gap` to styled-system reference table
How it's today: https://chakra-ui.com/docs/features/style-props#flexbox
Do not shows documentation for this props which was merged in https://github.com/chakra-ui/chakra-ui/pull/5123
Screenshot after changes: 
No
> [Styled-System] Adding gap to flexbox reference table

- configs/search-meta.json
- pages/docs/form/editable.mdx
Closes #381 
Adds `EditableTextarea` usage example and import.
No documentation for `EditableTextarea` component.
Adds `EditableTextarea` usage example and import.
No
> docs: Add example for `EditableTextarea`

- CONTRIBUTING.md
Would probably have a `yarn test`, but there are no tests 
Correcting a typo
Deleted unnecessary text
No
> [Contributing] typo

- next-redirect.js
Adds a next redirect for https://chakra-ui.com/guides/integrations/with-cra
This page got merged into the getting started cra guide
https://chakra-ui.com/guides/integrations/with-cra leads to a 404
https://chakra-ui.com/guides/integrations/with-cra is redirected to https://chakra-ui.com/guides/getting-started/cra-guide
No
> fix: add redirect for /guides/integrations/with-cra

- configs/guides-sidebar.json
- configs/search-meta.json
- pages/guides/integrations/with-capsize.mdx
Closes #157 
Added an integration page that showcases how to integrate Chakra UI with Capsize.
No
> docs(integrations): added Capsize integration page

- pages/guides/getting-started/remix-guide.mdx
Closes #220  
I've updated the documentation on how to implement Chakra UI with Remix.
The documentation is outdated and inaccurate.
The users will have accurate documentation regarding Remix and ChakraUI.
No.
/
> Updating Remix documentation on how to implement Chakra UI

- configs/guides-sidebar.json
- configs/sandpack-contents/formik-examples/login-form.js
- configs/sandpack-contents/formik-examples/plain-formik.js
- configs/sandpack-contents/formik-examples/simple.js
- configs/sandpack-contents/formik-examples/validation.js
- configs/search-meta.json
- pages/guides/integrations/with-formik.mdx
- src/components/sandpack-embed/index.tsx
Adding a Formik integration guide.
No
> docs(guides): Formik integration guide

- configs/search-meta.json
- pages/docs/components/layout/stack.mdx
Closes #411 
I've added VStack and HStack as titles in the Stack page, on top of that I've updated their description and the `Adding dividers`, I've changed to Stack Dividers for a more straight forward name + ease of searching.
No.
> Adding VStack and HStack in search-meta

- pages/docs/components/layout/container.mdx
Give the `Centering the children` section of the `container` component docs a live example. Update the description of the `contentCenter` prop to fix grammatical errors and state what CSS properties it renders. Update the example code to provide an acceptable preview.
> docs(container): Update the description and example code for the section "Centering the children", and render a live preview.

- pages/docs/components/form/input.mdx
Added a section for styling the placeholder of an input.
No information about styling the placeholder.
Section with examples for styling the placeholder.
No
> docs: add section for styling the inputs placeholder

- pages/faq/index.mdx
Added an answer to questions or issues when Storybook doesn't work with Chakra UI. Here's a reference: https://t.co/CBnAFyhhbN
N/A
N/A
No
> docs: added new question and answer for storybook

- package.json
Closes (already closed)
This bumps the codesandbox sandpack version to include the fix for the double history entries in firefox
Pages using sandboxes have double history entries on firefox
History should work as expected
No
See issue for linked PRs and Issues.
> chore: bump codesandbox to fix double history bug

- configs/resources.json
I've added the second video of Chakra Shorts.
It only has the first episode of Chakra Shorts.
It is updated with the latest video.
No.
> docs: adding second chakra shorts video

- configs/search-meta.json
- configs/styled-system-sidebar.json
- pages/docs/styled-system/component-hooks/use-checkbox-group.mdx
- pages/docs/styled-system/component-hooks/use-checkbox.mdx
- pages/docs/styled-system/component-hooks/use-radio-group.mdx
- pages/docs/styled-system/component-hooks/use-radio.mdx
Closes #406 
This PR adds two new docs pages for the `useRadio` and `useRadioGroup` hooks. It also provides exampls
No
This PR depends on the release of the [newly introduced types](https://github.com/chakra-ui/chakra-ui/pull/5708) for the state returned by the useRadio hook
> docs: add docs for radio hooks

- configs/guides-sidebar.json
- configs/sandpack-contents/prose/prose.js
- configs/search-meta.json
- pages/guides/recipes/prose.mdx
Closes #468 
This PR adds a recipe for the [Chakra UI Prose](https://github.com/nikolovlazar/chakra-ui-prose) package. I've also created a discussion thread (https://github.com/chakra-ui/chakra-ui-docs/discussions/469) to help us figure out if we need to move the Prose package into the core library.
No
> docs(prose): Added a Prose recipe

- .github/workflows/release.yml
- package.json
- yarn.lock
Closes https://github.com/chakra-ui/chakra-ui-docs/issues/481
Sibling PR on the main repo:
- https://github.com/chakra-ui/chakra-ui/pull/5831
I've added a Github action that generates the changelog and opens a PR whenever a dispatch event is sent from the main repo. 
It seems there is a daily cron job to check for this, this will make the process a lot easier.
The work will be automated and once the dispatch has been sent the changelog will be generated.
No.
@segunadebayo there is a workflow called `changelog`, I don't think we will need it now, should I remove it?
> ci: Adding github action to generate changelog based on dispatch

- .github/workflows/release.yml
Closes # 
Adding a manual trigger to release action
It is automatically triggered, we want to be able to trigger it manually.
We will be able to manually trigger it.
No.
> adding manual trigger for release workflow action

- pages/docs/components/form/form-control.mdx
Added `optionalIndicator` in https://github.com/chakra-ui/chakra-ui/pull/5618 and added some docs
> feat(form-control): add docs for optional indicator for `FormLabel`

- pages/docs/styled-system/overview.mdx
Closes # 
On the 'styled system' docs page you have a small typo - "styled stystem"
Link: https://chakra-ui.com/docs/styled-system/overview
It says "styled stystem" on the doc page (link above)
Typo fixed: "styled stystem" => "styled system"
No
> Fixing a small typo

- pages/docs/components/overlay/menu.mdx
Closes # 
there is not rootProps documentation in the doc
add rootpPops documentation
no
> add rootProps to menulist documentation

- configs/components-sidebar.ts
- configs/search-meta.json
- pages/docs/components/navigation/skip-nav.mdx
Create documentation for the `SkipNavLink` and `SkipNavContent` components. 
This includes one non-live example code and quick instructions to show how the link works as rendered on the docsite itself.
> docs(skip-nav): create documentation for the skip nav component set

- configs/search-meta.json
- pages/docs/styled-system/component-hooks/use-radio-group.mdx
Closes #542 
Adds documentation and an example on the usage with the `isDisabled` or `isFocusable` prop.
> docs(use-radio-group): add section on using `isDisabled`/`isFocusable`

- pages/docs/components/form/radio.mdx
Add links in the "Custom Radio Buttons" section of the `Radio` docs to let users be able to visit the dedicated pages for the component hooks.
> docs(radio): add links in "Custom Radio Buttons" section to the component hooks

- pages/docs/components/feedback/alert.mdx
Quick fix: Reintroduced from PR #535 when it was intentionally removed via PR #534
> fix(alert): remove `CloseButton` from basic usage example

- pages/guides/getting-started/remix-guide.mdx
> Add installation command for remix using yarn. Could have changed the label "Inside your Remix project root directory, install Chakra UI by running the following:" to singular but chose to add instructions for yarn instead.
> docs: add yarn installation command for remix

- pages/docs/components/form/button.mdx
Closes # 
Update docs according to changes in https://github.com/chakra-ui/chakra-ui/pull/5754
> docs(button): Update ButtonGroup example

- README.md
- src/components/version-switcher.tsx
Closes # 
Adds links to v1
Only v0 was linked in the docs
V1 is added to this list of versions everywhere.
No
> docs: add v1 backlink

- configs/guides-sidebar.json
- pages/guides/migration.mdx
Closes # 
Adds migration guide to migration from chakra v1 to chakra v2.
> docs: add migration guide for v2

- pages/docs/components/feedback/toast.mdx
Update the docs of `createStandaloneToast` to reflect the changes of v2.
No
> docs: createStandaloneToast v2

- pages/guides/integrations/with-storybook.mdx
Update the docs of storybook-addon to reflect the changes of v2.
No
> docs: update docs for storybook-addon v2

- pages/docs/components/feedback/alert.mdx
Closes # 
fix small typo on Alert docs page
> docs: fix typo

- configs/search-meta.json
- pages/changelog/index.mdx
Add changelog and search to v2 release
> chore: add changelog and search

- pages/docs/components/form/button.mdx
Closes # 
Add ColorScheme examples for `<Button />` component
Current examples for the Button component don't include the possible color variants of the Button component.
Shows examples for every possible color scheme of a Button component.
No
> chore(docs): add colorSchemes examples to button component

- pages/docs/styled-system/features/text-and-layer-styles.mdx
Relates to [6058](https://github.com/chakra-ui/chakra-ui/issues/6058)
Add the precedence order to the layer styles page to avoid confusion (and unnecessary feature requests :D)
> docs: add layer/variant precedence to layer styles page

- scripts/get-showcase-data.ts
> refactor(get-showcase-data): cleanup linting issues

- package.json
- scripts/avatars.ts
- scripts/image-cache.ts
- yarn.lock
Closes #634 
Remove imagemin packages
- unnecessary image compress packages
- unused code
- removed the packages and the code which used it in the past
No
> chore: remove imagemin packages and dead code

- pages/docs/styled-system/features/color-mode.mdx
fixed a small typo in color-mode docs
> docs: typo correction in color-mode

- .all-former-membersrc
- .github/workflows/daily.yml
- i18n/ui.json
- package.json
- pages/team.tsx
- scripts/get-former-members.ts
- scripts/get-showcase-data.ts
Closes #430
New section for former core team members.
- script that fetches former core members from [HALL_OF_MAINTAINERS.md](https://github.com/chakra-ui/chakra-ui/blob/main/HALL_OF_MAINTAINERS.md)
- script is includes in daily cron job
- section for former core members on team page
No
> docs: section for former core members on team page

- pages/guides/integrations/with-hook-form.mdx
`CSSReset` is provided by `ChakraProvider`, so no need to provide it by yourself.
No
Where `CSSReset` is called in `ChakraProvider`
https://github.com/chakra-ui/chakra-ui/blob/4449b7fdd5de8bab1cb690b7d0f86bd71f6e4650/packages/provider/src/chakra-provider.tsx#L86
> chore: remove CSSReset in sample code

- CONTRIBUTING.md
- pages/guides/advanced/contributing.mdx
Update of projects scripts documentation.
> docs: update list of commands

- configs/search-meta.json
- pages/docs/styled-system/theming/customize-theme.mdx
Closes #640 
Add a section for responsive variants and small improvements for existing docs.
No section for the new feature.
- section for the new feature
- improvement of docs for `defaultProps` in components theme overwrite
- add typing for multiple objects in theme context
No.
Since I could not find informations about this feature I just tried stuff and documented as good as I could. If anything is missing in the docs for the feature let me know. :)
> docs: add section for responsive variants

- pages/docs/components/typography/heading.mdx
- pages/docs/components/typography/text.mdx
Closes #674 
> Remove redundant section to make docs clearer
> docs(text): make noOfLines prop consistent

- pages/docs/styled-system/features/color-mode.mdx
Fix typos in "Color Mode" page
> docs(features): Fix typos

- configs/search-meta.json
- pages/docs/components/feedback/skeleton.mdx
Closes #685
Add description of `fadeDuration` prop usage with example as it relates to the `isLoaded` prop. Thanks to @itkrt2y with his [CSB example](https://github.com/chakra-ui/chakra-ui/issues/6126#issuecomment-1140855638)!
After next package release, the Prop Table will be up-to-date. See [ChakraUI PR #6178](https://github.com/chakra-ui/chakra-ui/pull/6178)
> docs(skeleton): add section for `fadeDuration` prop

- content/docs/components/container/usage.mdx
Broken link in the Container Document related to theme sizes.
Closes # 
> Updating Container Document Link

- content/community/recipes/using-fonts.mdx
- content/community/recipes/z-index.mdx
- content/docs/components/badge/usage.mdx
- content/docs/components/icon/usage.mdx
- content/docs/styled-system/advanced-theming.mdx
- content/docs/styled-system/component-style.mdx
- content/docs/styled-system/customize-theme.mdx
- content/docs/styled-system/the-sx-prop.mdx
- content/docs/styled-system/theme.mdx
- content/getting-started/gatsby-guide.mdx
- content/getting-started/principles.mdx
- content/getting-started/redwoodjs-guide.mdx
- next-redirect.js
Related to #747
1. Add redirects for broken segments in paths : 
-  /styled-system/features => Redirect to /styled-system
- /styled-system/theming => Redirect to /styled-system
2. Fix the files using that broken segments in docs
404 pages
Working links, internaly and old links too.
No
First open source contribution ever !
> fix: redirect for /styled-system/features segments in path

- content/docs/styled-system/customize-theme.mdx
Closes # 
Small typo in the "customize-theme" page
- The font size of the "sm variant" is lg but the comment says it is "xl"
- change xl to lg in the comment
No
> Small typo in "customize-theme" page

- CONTRIBUTING.md
Updates the documentation in `CONTRIBUTING.md` to clarify that `GITHUB_TOKEN` should be added to an `.env` file in the local repo to be used successfully when running APIs in scripts. 
Running an export command in the terminal to apply this variable might not always work for every user.
> docs(CONTRIBUTING): update instruction on `GITHUB_TOKEN`

- content/getting-started/cra-guide.mdx
Closes # 
Removing the last line telling us if we want to generate cra template from scratch. The link is also wrong.
No
> fix(docs): removing line wrong redirecting to cra guide

- README.md
Closes #807 
In the README the license link opens up the image, It would be useful if it went to the MIT license page.
> docs(license): link added to license badge #807

- content/getting-started/contributing.mdx
Updates the [Contributing page](https://chakra-ui.com/getting-started/contributing) content to match the updated markdown file.
> docs(contributing): update page to matching markdown file

- content/docs/components/input/usage.mdx
Closes # 
The documentation page just shows examples on text and password as input. It would be a great addition to show more examples such as date, month, time and color picker inputs. I saw reddits and stackoverflow questions asking for date and time picker exclusively not being available in Chakra UI as Material UI and ANTD.
No Mention of any other input methods supported by Chakra UI Input. Users expect exclusive date time pickers similar to Material UI and ANTD.
Added examples on other input methods for the users.
Somewhat - need to install 3rd party libraries for specific components.
> Add more examples of different Input Methods

- content/docs/styled-system/color-mode.mdx
Update docs for this change: https://github.com/chakra-ui/chakra-ui/blob/main/CHANGELOG.md#17-05-2022-1
> [Docs](https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr) says `cookieStorageManager`
> [Docs](https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr) should say `cookieStorageManagerSSR`
> To test: https://chakra-ui-docs-git-fork-henrituan-docs-update-7bf6f0-chakra-ui.vercel.app/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr
Related issue: https://github.com/chakra-ui/chakra-ui/issues/6175
> docs: chage cookieStorageManager to cookieStorageManagerSSR

- configs/search-meta.json
Closes #831
Adding Highlight component in search meta
Highlight component not being able to access from search
Highlight component accessible from search
No
> docs(search): add highlight component in search meta

- content/getting-started/index.mdx
Closes #809 
Add note to the `Installation` page that Chakra UI v2 is only compatible with React 18.
> docs(getting-started): add note that v2 is only compatible with React 18

- next.config.js
Update the `next.config.js` file where the `experimental` options given are outdated compared to the current signature.
`optimizeFonts` is no longer experimental, and `modern` is no a part of the config.
This does not produce any significant changes to the site, but can prevent builds from failing when `contentlayer` needs to be bumped. (Currently the deployment check in PR #827 is failing for this very reason)
> Update Next Config

- content/docs/components/input/usage.mdx
> docs(input): remove bgColor from DateTimePicker breaking dark mode view

- content/docs/hooks/use-breakpoint-value.mdx
The documentation doesn't really make it clear that you can define what breakpoint to use by default. I've just modified it to mention this.
> Clarify the parameters for useBreakpointValue

- content/docs/components/input/theming.mdx
Adds basic information to the Input theming docs.
I couldn't find good info on the docs site. After a bit of github issues/discussions navigation I found out Input is a multipart component.
On the Input docs there's an empty theme tab. It could be useful to have some basic info there.
Now people will be able to see some basic info, like the fact that the Input is a multipart component, as well as a couple of links to make it easier for them to know what to change.
No
To be honest, I didn't see the Theming tab under the component docs before. This will be quite helpful (I think) for people that see them, though.
> Add some basic info on the Input theming docs

- content/docs/styled-system/theme.mdx
> docs(default-theme): spread borderRadius in extendTheme

- .github/workflows/contributing.yml
- package.json
- scripts/build-contributing-page.ts
Created a script with a github workflow to automate the (re)creation of the `contributing.mdx` file if `CONTRIBUTING.md` is ever updated.
> build: create script to auto generate contributing page on file update.

- content/docs/components/input/usage.mdx
> Changed placeHolder -> placeholder

- chakra-users.ts
Closes # 
#900 
> Update shootproof url from [this](https://www.shootproof.com/hp) to [this](https://www.shootproof.com/)
> Update url that open to "page not found" page
> If click shootproof logo now will go to [here](https://www.shootproof.com/)
No
> fix: update shootproof url

- LICENSE
Closes #920 
This PR adds an MIT License file
No license file. The MIT license is mentioned only at the bottom of the README file.
Added a LICENSE file.
No
> docs(license): adding license file

- package.json
- src/components/algolia-search.tsx
- src/components/search.styles.tsx
- yarn.lock
Reverts chakra-ui/chakra-ui-docs#924
> Revert "build(deps): bump @docsearch/react from 1.0.0-alpha.28 to 3.2.1"

- content/docs/components/input/theming.mdx
This PR does two things:
- Fixes broken links (originally opened as #926, but will close in favor of this PR)
- Adds small example to showcase how to extend the theme of the input component.
Links are broken, and there's no example.
Links work, and there's an example.
No
I tried to make an example where I could show the resulting input in the page. Similar to other places in the docs where I can see the component with the code that generated it immediately below.
After looking at the source of docs that have that kind of examples, and trying a few things, I didn't manage to get it working. This was my first time using mdx, so I'm probably missing something that would make that task simpler.
Feel free to add the resulting component, or let me know how to do it so I can add a new commit to …
> Input theming example

- content/docs/components/heading/props.mdx
- content/docs/components/text/props.mdx
- package.json
- pnpm-lock.yaml
- src/components/chakra-next-image.tsx
> refactor(dependencies): bump chakra versions + dependencies fixes

- content/getting-started/remix-guide.mdx
Update docs for remix-guide to fix color mode flashing issue in `remix`
> Add colorModeManager to remix-guide to fix color mode `flashing`

- src/components/mdx-components/component-links.tsx
> chore: new component links

- content/docs/styled-system/theme.mdx
Closes #953
Fixed broken link in default theme page.
> fix(docs): fixed broken link in default theme page

- content/docs/styled-system/style-props.mdx
Closes # 
Fix `overflowX` and `overflowY` to match the correct `overflow-*` css props
> Update style-props.mdx to match overflow props to correct CSS props

- content/docs/styled-system/customize-theme.mdx
Closes # 
Fix the broken link for
Change the link because it got 404 not found response
New link
No
> Fix broken link for default component style files

- content/docs/components/input/theming.mdx
Current [link](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/input.ts) is not right
No
> fix(input): Update link to the input component

- content/docs/components/input/usage.mdx
Matches code formatting style for this example.
Editable code example has four spaces
Two spaces
No
None
> chore: match code formatting style

- .github/workflows/release.yml
Closes # 
The release action is failing because of the missing `changelog:gen`. This PR removes the script from the action.
> chore: remove changelog:gen script from action

- content/docs/components/aspect-ratio/usage.mdx
The <iframe> element doesn't support an alt attribute.
The <iframe> element has an alt attribute.
Remove the alt attribute in the <iframe> element.
I'm a novice, and this is my first time using Pull Request. Please correct me if there is any omission, thanks 😀
> docs: update usage.mdx of Aspect Ratio component

- configs/sandpack-contents/component-theming/button.js
- content/docs/components/button/theming.mdx
Closes #1041
Adding `Button` theming docs
> feature(docs): adding button component theming docs

- configs/sandpack-contents/component-theming/heading.js
- content/docs/components/heading/theming.mdx
Closes #1074 
> Added docs for theming headings.
> Adds docs for theming headings
> docs: added heading theming docs following the new template

- configs/sandpack-contents/component-theming/divider.js
- content/docs/components/divider/theming.mdx
Closes #1073 
> Added docs for theming `Divider`
> Adds docs for theming `Divider`
> docs(theming): added docs for theming dividers

- configs/sandpack-contents/component-theming/badge.js
- content/docs/components/badge/theming.mdx
Closes #1039 
Adding theming docs for the `Badge` component
>  feature(docs): badge component theming

- configs/sandpack-contents/component-theming/icon-button.js
- configs/sandpack-contents/component-theming/textarea.js
- content/docs/components/icon-button/theming.mdx
Closes #1049 
The goal of this pull request is to add theming for the `IconButton` component.
Currently, there is no theming documentation for this component.
Now, all the users of Chakra UI will have proper documentation on how to style the `IconButton` component.
No.
On top of that, the colors for the TextField in dark mode were wrong, I have added proper styling there.
> feature: Adding theming for IconButton

- configs/sandpack-contents/component-theming/container.js
- content/docs/components/container/theming.mdx
Closes #1046 
Add `Container` component theming docs and corresponding Sandpack.
> feat(docs): add container component theming docs

- content/docs/hooks/use-media-query.mdx
Closes #504
Adding an SSR block for the `useMediaQuery` docs.
No SSR block.
Yes SSR block 😁
No
> feature(docs): added ssr docs for useMediaQuery

- content/docs/styled-system/component-style.mdx
Closes #656
Added a block for Responsive Modifiers (variants and sizes).
> feature(docs): added docs block for responsive modifiers

- content/getting-started/migration.mdx
> feature(docs): v2 migration additions

- content/getting-started/migration.mdx
> feature(docs): clarified isTruncated migration docs

- content/getting-started/nextjs-guide.mdx
Closes #1172
Closes #1169
Adding a Next.js 13 integration docs.
> feature(docs): next 13 integration docs

- content/docs/components/link/usage.mdx
Closes #1196
Added two examples on how to use Next.js 13's `Link` component with Chakra UI.
> feature(docs): added docs for next 13 link

- configs/components.sidebar.json
- content/docs/components/card/props.mdx
- content/docs/components/card/theming.mdx
- content/docs/components/card/usage.mdx
- pnpm-lock.yaml
- public/components/card.svg
- src/components/mdx-components/codeblock/react-live-scope.tsx
This PR adds the documentation for Card component
> There's currently no Card component so this is a new feature
> This PR adds the documentation for Card component
No
> Add card component docs

- configs/getting-started.sidebar.json
- src/components/sidebar/sidebar-link.tsx
- src/components/sidebar/sidebar.tsx
- src/utils/get-route-context.ts
Closes #1237 
The goal of this pull request is to add the roadmap to the sidebar.
Currently, the roadmap isn't available on the documentation website.
Now, the users will easily access the roadmap.
No.
> feature: adding roadmap to sidebar

- content/docs/components/drawer/usage.mdx
small typo in the description of Drawer component
> Fixed typo in Drawer component description
> No
> docs: fix typo in Drawer component description

- content/docs/styled-system/chakra-factory.mdx
📝 Description
This PR fix stale link for the list of Chakra supported HTML elements
> docs(features): fix stale link

- content/docs/components/divider/theming.mdx
> docs: added missing comma

- configs/sandpack-contents/component-theming/code.js
- content/docs/components/code/theming.mdx
added new code component theming. (single-part component)
Add theming tab in Code component and stuff required for sandpack embed.
No
referenced: Button theming config, badge theme from which code imports variants
> Feat: added code theming

- configs/sandpack-contents/component-theming/code.js
- content/docs/components/code/theming.mdx
Closes #1045 
Adding `Code` theming docs.
> docs(theming): code theming docs

- configs/showcase.json
Showcase change: Updated the snappify URL to .com and changed the name to lowercase.
No
> showcase: updated snappify url

- content/docs/components/skip-nav/usage.mdx
Fixes a misspelling and small grammar issue in the docs for the "SkipNav" components.
The word "sufficient" is spelled wrong. It's also paired with "enough," while the word "sufficient" by itself is... well... sufficient 😄
I corrected the typo and removed the unneeded word.
No
> docs: fix spelling/usage of "sufficient"

- pages/docs/components/index.tsx
> docs: deleted unnecessary round bracket

- README.md
Closes #1341
The goal of this pull request is to fix the broken logo URL in the README.md (see issue).
The URL is broken since the structure of where the logo is has changed on the main repo.
Adjusts the URL and now the URL isn't broken anymore.
No.
> feature: Fixing logo URL in README.md

- configs/sandpack-contents/component-theming/skeleton.js
Just cleaned up the theming for the Skeleton component.
Added better colors to the skeletons so they are good in contrast to the background.
Better colors in the examples and changed up the text as well.
No.
> feature: cleaning up theming for the skeleton component

- configs/components.sidebar.json
- configs/getting-started.sidebar.json
- src/components/sidebar/sidebar.tsx
Closes #1410
The goal of this pull request is to add the new playground url to the navigation of the docs.
Currently, there is no URL to the playground.
Now, there will be a URL where the users can play around with Chakra UI.
No.
> Adding playground in navigation

- configs/search-meta.json
- content/getting-started/nextjs-guide.mdx
- pnpm-lock.yaml
<!---
This PR documents how Chakra UI provides a `@chakra-ui/next-js` package that gives a better experience when using Next.js 13 app directory.  It also explains how this package allows a smoother use of Chakra Link with `next/link`.
There's currently no detailed documentation of Next.js support.
This PR documents how Chakra UI provides a `@chakra-ui/next-js` package that gives a better experience when using Next.js 13 app directory.  It also explains how this package allows a smoother use of Chakra Link with `next/link`.
No
> docs: Next.js 13 support

- configs/search-meta.json
- content/docs/components/center/usage.mdx
Closes # [1147](https://github.com/chakra-ui/chakra-ui-docs/issues/1147)
Add info about `AbsoluteCenter` component to Layout/Center.
No
> docs(center): add absolutecenter component info

- content/getting-started/remix-guide.mdx
> docs(remix-guide): fix typo

- pages/search.tsx
- src/components/omni-search.tsx
> feat: add search page for testing

- configs/search-meta.json
- content/docs/components/accordion/theming.mdx
- content/docs/components/modal/theming.mdx
> refactor: add headers to theming

- content/docs/components/link-overlay/usage.mdx
Updates usage with next.js links
Current implementation results in invalid dom, and also does not properly wrap the component with a link. It also breaks next.js routing.
By passing in `NextLink` directly to the `LinkOverlay`, behaviour is preserved and next.js routing is respected.
No, just a doc change.
> Updates usage with next.js routing library

- content/docs/styled-system/component-style.mdx
- Fix small typo in [`useMultiStyleConfig` props section](https://chakra-ui.com/docs/styled-system/component-style#parameters-1)
- Use same description as [`useStyleConfig` props section](https://chakra-ui.com/docs/styled-system/component-style#usestyleconfig-api)
- N/A
- No new behavior
- No
> docs (styled-system): Fix useMultiStyleConfig typo

- content/community/recipes/using-fonts.mdx
Closes # 
fixed where to add it if using create-react-app and added import option even into the theme file
No
> fix on cra and import options

- content/docs/components/heading/theming.mdx
Fixed a small typo in heading theming.
No
> docs(heading): fix typo

- content/docs/components/modal/usage.mdx
The PR adds cosmetic changes that improve the clarity of the document
At least one word was ommitted and or used wrongly.
This PR inserted the ommited wor and corrected the affected tense.
No.
> Insert ommitted word and verb ending

- content/docs/components/toast/usage.mdx
Closes #1523
Correct import from for standalone toast usage.
People trying to install `@chakra-ui/toast`
People can import from `@chakra-ui/react`
No
> docs: update toast standalone usage

- configs/search-meta.json
- pages/docs/components/index.tsx
Closes #1552 
>  added component search feature at `/docs/components`
>  You can now search components by their names at the overview page
>  Add search feature to component overview page

- configs/search-meta.json
- content/getting-started/gatsby-guide.mdx
Closes #1549 
Updates the Gatsby Guide Page to
- Include installation with Gatsby starter
- Update usage example to the latest implementation
> docs(gatsby-guide): update usage and include starter

- content/docs/components/toast/props.mdx
Closes https://github.com/chakra-ui/chakra-ui-docs/issues/1608
Fixed toast props page.
There was no information on the toast props page.
People can view toast props.
No
> fix: toast props page

- content/docs/components/button/usage.mdx
Nit doc fix: change order of variants to be consistent with example
No
> Nit fix: change order of variants to be consistent with example

- content/docs/components/toast/usage.mdx
Added a section with an example for promise based toasts.
Closes # 
> just added a how to for promise toasks
> N/A
> N/A
> toast: add promise based usage

- configs/search-meta.json
- content/docs/components/toast/usage.mdx
Closes #1660
This PR fixes the broken promise-based toast example.
The promised-based toast example shows an error message due to syntax error.
The error message no longer exists after the adjustment of the example code.
No.
Some changes are made by Prettier while formatting.
> Fix broken promised-based toast example

- content/docs/styled-system/customize-theme.mdx
> Update customize-theme.mdx (fix typo)

- content/docs/components/modal/theming.mdx
- content/docs/styled-system/customize-theme.mdx
- content/docs/styled-system/theme.mdx
- src/components/mdx-components/component-links.tsx
Closes #1693 
link is broken. (404 not found)
No
> fix(docs): fixed link

- content/getting-started/index.mdx
<s>Closes # </s> (no issue)
Hi! I think there is a typo in documentation. Should be both `theme` or `_theme`
Error when I paste the code: `Cannot find name '_theme'. Did you mean 'theme'?`
No error
No
> Fix typo in index.mdx

- configs/search-meta.json
- content/docs/hooks/use-clipboard.mdx
Closes https://github.com/chakra-ui/chakra-ui/issues/7754
All details written in implementation PR: https://github.com/chakra-ui/chakra-ui/pull/7761
> Add imperative section
