package.json
pages/index.tsx
pages/team.tsx
src/components/language-switcher.tsx
src/utils/i18n.ts

Closes #17
This PR removes on-demand loading of i18n strings, therefore it fixes the localized string flickering. A better i18n implementation should be worked out in future.
Homepage title (and more strings in team page) flicker before i18n loads the strings in memory.
No flickering
No

docs(i18n): fixed i18n flickering + commented out the language switcher component

---

i18n/ui.json
pages/index.tsx

This PR fixes #19 
Changes the `with speed` text in `homepage.title` to `teal` color.

Fix Homepage Headline Color

---

src/components/version-switcher.tsx

Closes #18 
Added the latest chakra version used in docs to the version picker dropdown.
The current chakra version shows v1.x.x. 
The dropdown now shows the latest version of chakra ui installed in the docs repo as default.
No
-

fix: add latest chakra version used in docs to version picker

---

pages/docs/disclosure/visually-hidden.mdx

Closes #46 
Adds VisualHiddenInput Documentation to the `visually-hidden.mdx` file.
Currently, the documentation for the component `VisualHiddenInput` is missing. 
This PR adds the docs for the component.
No.
Suggestions/Improvements are welcomed around:
- Examples
- Explanation
- Structure.
Find changes at `/docs/disclosure/visually-hidden` route.

Added Documentation for VisualHiddenInput Component

---

CONTRIBUTING.md

This just fixes the path of chakra-ui-docs after cloning.

docs: fixed repo path in CONTRIBUTING.md

---

pages/docs/[[...slug]].tsx
pages/guides/[[...slug]].tsx

Closes #68 
The `Link` doc page wasn't being targeted correctly, so the `LinkOverlay` page was rendered instead. Instead of `.includes`, I've replaced the query with `endsWith`, and then added an `.mdx`. This way the `Link` doc page gets rendered correctly. I also checked every other page in the documentation. No issues there.
`Link` docpage doesn't get rendered
All good 👍 
No

fix(docs): fixed MDX targeting in docs

---

i18n/ui.json
src/components/mobile-nav.tsx

Closes #36 
Adds the resource link to mobile nav. Modified link display from HStack to Grid to support all new Links.
No link to the resource page on the mobile navigation
Mobile navigation now also has a link to the resource page
No

fix(mobile-nav): add resource link

---

pages/docs/media-and-icons/image.mdx

Fixed broken links for the image component in the [documentation](https://chakra-ui.com/docs/media-and-icons/image)
'https://bit.ly/sage-adebayo' link is broken
Replaced 'https://bit.ly/sage-adebayo' link with 'https://bit.ly/dan-abramov' as the former link is broken.
Fixed [documentation page](https://chakra-ui-docs-git-fork-6aravind-docs-fix-links-chakra-ui.vercel.app/docs/media-and-icons/image)
No

Fixed broken links for the image component

---

pages/index.tsx

Updated the numbers in the growing section to match new values.
Homepage growing section was still showing 488k monthly downloads and 2.9k discord members
Homepage growing section is showing 813k monthly downloads and 5.1k discords members
No

chore: update numbers in the growing section

---

scripts/get-showcase-data.ts

Skipped script execution if GitHub URL is not a repo URL.
The Daily script crashes with `TypeError: Cannot read property 'owner' of undefined`.
All good now.
No

docs(scripts): fixed showcase script GitHub URL destructuring

---

.github/workflows/daily.yml

The `commit showcase.json` GitHub action has a typo and cannot commit the `showcase.json` file.
The GitHub Daily action fails because there is no `config/showcase.json` file.
I changed the targeting to `configs/showcase.json`.
No

docs(scripts): fixed commit showcase bug

---

pages/docs/theming/customize-theme.mdx

I had difficulties to find a way to define in the theme a color that changes depending on the color mode.
This is handy so I don't need to handle it inside of each component (with `useColorModeValue`).
I don't know if I am missing something else from the documentation, but I wish I would have found sooner the mention of the function `mode` from `@chakra-ui/theme-tools`.

doc: mention color "mode" function in the doc

---

pages/index.tsx
src/utils/get-discord-members.ts
src/utils/get-github-stars.ts
src/utils/get-npm-downloads.ts
src/utils/number-formatter.ts

Closes #98 
Need to automate the npm downloads and discord guild member count.
Currently, the npm downloads and discord guild member count is hardcoded which is really not efficient.
After this PR merged, it will be automated at build time by fetching to some specific API endpoints.
No
None

feat(homepage): Automate npm downloads and discord guild member count

---

pages/docs/form/form-control.mdx

Closes https://github.com/chakra-ui/chakra-ui-docs/issues/146
In the examples of `FormControl`, assign `FormLabel` with its controls
Clicking on the labels won't make controls focused
Clicking on the labels focuses the controls

docs(form-control): assign form controls with its labels

---

pages/docs/navigation/link.mdx

Added "Usage with Next.js" section, Using Next.js Link with Chakra-UI link is not the same as using it with Reach Router or React Router.
There is no official docs about how to use Next.js Link with Chakra-UI link.
Added a section about how to use Next.js Link with Chakra-UI Link.
No

docs(link): Added "Usage with Next.js" section

---

pages/docs/theming/customize-theme.mdx

I am sorry, but this is not working as expected.
The `mode()` utility function is not meant to be used in the color section, because it expects only static values. 
I'll come back with a better contribution and example, sorry about that.
Reverts chakra-ui/chakra-ui-docs#140

Revert "doc: mention color "mode" function in the doc"

---

src/utils/get-discord-members.ts

Previously I'm trying to automate the discord member count by creating a request to the discord invite url with the invite id (I guess), and It just temporary, when it gets expired, the response return undefined, and parsed by number formatter and it give us NaN.
I've updated the invites link to use `chakra-ui`.
This should fix below behaviour
No
Here's the screenshot

fix(homepage): discord member NaN

---

pages/docs/form/form-control.mdx

Closes #73 
- A simple example for showing the use case of `FromErrorMessage`
- Descriptions about 4 components exporting from `form-control`
Lack detail descriptions and sample usages about `FormErrorMessage` and `FormHelperText`. 
No

docs(FormControl): an example of FormErrorMessage and some descriptions 

---

pages/docs/form/slider.mdx

Closes #78 
Add 2 example to show how to add a mark on `SliderThumb`
- With `SliderMark`
- With `Tooltip`
No example for adding marks on thumb
- With `SliderMarks`
- 
- With `Tooltip`
- 
No

docs(slider): Add SliderMarks example

---

pages/docs/overlay/menu.mdx

Closes #166
> Remove MenuIcon, MenuCommand from import
> No

Remove MenuIcon, MenuCommand from import as it is only used inside chakra-ui source code

---

pages/docs/form/checkbox.mdx
src/components/props-table.tsx

Closes #142 
Update one of the Checkbox examples, within Checkbox documentation page, to prevent it from overflowing container on mobile, and thus, prevent the bug.
_Before_
_After (current)_
* Checkbox example breaks out of container in documentation page, at smaller view ports
* Checkbox example no longer breaks out of container in documentation page, at smaller view ports
* Example still uses row layout, whenever there is space, but then switches to column whenever there is no space
No
* Tested on Edge, Firefox, and Chrome

Fix Checkbox Doc Example On Mobile Layout

---

pages/docs/layout/grid.mdx

We do not import Box at the beginning of this page. So I think, we should use GridItem instead.
Closes # 
Use GridItem composent instead of Box
No

fix: Use GridItem instead of Box

---

pages/docs/getting-started.mdx
pages/guides/getting-started/cra-guide.mdx
pages/guides/getting-started/nextjs-guide.mdx
pages/guides/getting-started/redwoodjs-guide.mdx
pages/guides/getting-started/remix-guide.mdx
pages/guides/with-nextjs.mdx

This PR updates `framer-motion@^4` to `framer-motion@^5`
https://chakra-ui.com/docs/getting-started uses `framer-motion@^4` but https://github.com/chakra-ui/chakra-ui/#installing-chakra-ui uses `framer-motion@^5`.
```
npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4
```
Both https://chakra-ui.com/docs/getting-started and https://github.com/chakra-ui/chakra-ui/#installing-chakra-ui use `framer-motion@^5`.
```
npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^5
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^5
```
No.
https://chakra-ui.com/docs/getting-started

docs(guides): update framer-motion to v5

---

pages/docs/features/style-props.mdx

So this PR removes the misleading example of using fractional values for layout sizes which should be converted into percentage values.
When following the style-props docs, it is shown that using the following `<Box w={1/2} />` will give you a `50%` width, but in fact, you get the value representation of `var(--chakra-sizes-0\.5)` which is `0.125rem`.
This has been reported in the following issues: chakra-ui/chakra-ui#3396 chakra-ui/chakra-ui#3777 chakra-ui/chakra-ui#3673
See https://github.com/chakra-ui/chakra-ui/issues/3396#issuecomment-790407805

docs(style-props): remove fractional code example

---

pages/guides/integrations/with-framer.mdx

Also, in codesandbox edit link, this snippet 
```jsx
type Merge<P, T> = Omit<P, keyof T> & T;
type MotionBoxProps = Merge<HTMLChakraProps<"div">, HTMLMotionProps<"div">>;
export const MotionBox: React.FC<MotionBoxProps> = motion(chakra.div);
```
can be commented out (if the below snippet generate Typescript error, _see P/S_) and replaced by
```jsx
export const MotionBox = motion<BoxProps>(Box);
```
---
P/S: Example error using the replaced snippet
```jsx
export const TextMotion = motion<TextProps>(Text);
<TextMotion
fontSize="2xl"
fontWeight="semibold"
fontFamily="cursive"
w="100%"
borderBottom="1px solid white"
initial={{ x: 1000 }}
animate={{ x: 0 }}
transition={{ duration: 5 }} // <-- Error here
>
Pizza Join
</TextMotion>
/*
Type '{ duration: number; }' is not assignable to type …
```

Typo in typescript code

---

next.config.js

Closes #103 
Enable source map in production mode 
Allow users to see the original code.
According to the nextjs doc, there are two caveats if we turn on `productionBrowserSourceMaps` 
- Increase building time when we run `next build`
- Increase memory usage when we're running `next build`
No

enhancemenet: enable source map in production mode

---

pages/docs/overlay/popover.mdx

Closes #183
Removes the `enabled` prop from Popover documentation
`enabled` prop is shown in Popover documentation but is omitted from types as per https://github.com/chakra-ui/chakra-ui/issues/5155#issuecomment-984784300
`enabled` prop is no longer shown in Popover documentation
No

docs(popover): omit enabled prop, resolves #183

---

pages/docs/media-and-icons/icon.mdx

Closes #178 
> The doc page for Icon contains the View theme source button, but there is no theme source for Icon. Clicking on the button produces a 404 page, so removed `View theme source` button from icon docs.
> Currently, when you click `View theme source` button on icon docs, users land on 404 page
> As there is no theme source for icon, we removed the corresponding button from docs
Screenshot:

docs(icon): remove view theme source button from icon docs

---

pages/docs/hooks/use-clipboard.mdx

Closes # 
The useClipboard documentation wasn't super clear, so I added information about defaults & units. I'm not particular about the language used, but it would be nice to have the default timeout of 1500ms specified!
The `optionsOrTimeout` parameter is confusing.
Adds more details about `optionsOrTimeout`.
No
Perhaps it would be even better if `optionsOrTimeout` was replaced with two parameters in the code, `options` and `timeout`. Then each idea is its own discrete unit that can be understood without reference to the other, reducing mental load.

Clarify the useClipboard timeout parameter

---

configs/docs-sidebar.json

Fixes the order of Pagination for the hooks docs. Specifically the order of `useConst` and its previous and next order in its sibling pages.
There is a disorder of navigation on the pages and skips back an extra page on the siblings of `useConst`/`useControllable`
Pagination works as expected.
No

fix(docs): Fix pagination order in hooks docs

---

pages/docs/features/style-props.mdx

Closes # NA
Removes duplicate style prop definition for `objectPosition`. 
Currently, under the style props documentation, there is a duplicate definition for `objectPosition`. 
This pull request removes the duplicate definition for `objectPosition` from the style props documentation.
No.
NA

docs: remove duplicate objectPosition prop definition

---

pages/docs/disclosure/tabs.mdx

Closes #76 
Modified the example for custom Tabs and removed the broken parts. Replaced them with the useMultiStylesConfig API.
Type errors when using the factory with themeKey the example.
No more type errors and example working as expected when pasting.
No
-

docs(tabs): fix the Tabs example to work properly and without type errors

---

pages/docs/overlay/popover.mdx

Our team was trying to get a button to focus in a Popover with a `hover` trigger. We would've saved a bunch of time if we found this comment earlier: https://github.com/chakra-ui/chakra-ui/issues/3820#issuecomment-820535397
Therefore I thought it could be helpful to clarify that in the Popover documentation
This PR adds a note to the Popover documentation (see below)
n/a
No

docs: clarify when initialFocusRef can be used on Popover

---

pages/faqs/index.mdx

Rewords the FAQ to remove the word "easily", which can be taken as condescending.

Remove inconsiderate language from FAQ

---

pages/index.tsx
src/components/chakra-next-image.tsx

Closes #239 
Fix logo image's objectFit property.
Updates the `objectFit` property from `cover` to `contain`.
No

fix: sponsor logos objectFit property

---

pages/index.tsx

Closes #238 
Redesign the supporter logos on the homepage, limiting them to 7.
Currently, there are 8 supporter logos shown. As per issue description, we wish to replace the 8th one with `Your company` text.
The New updated design looks like below:
No

feat: homepage logo redesign for supporters

---

pages/docs/comparison.mdx

Fixes a small typo in the docs: "rangining" should read "ranging"

docs: fix typo in "ranging"

---

pages/docs/theming/component-style.mdx

Adds `{children}`to theming example @ https://chakra-ui.com/docs/theming/component-style#return-value
Theming example destructs `children` in line 222 but doesn't return it
removes destructed `children` from theming example props
No

docs: fix missing children in theming example

---

pages/changelog/content.mdx
pages/docs/features/chakra-factory.mdx
pages/docs/features/color-mode.mdx
pages/docs/features/semantic-tokens.mdx
pages/docs/hooks/use-prefers-reduced-motion.mdx
pages/docs/theming/component-style.mdx
pages/guides/as-prop.mdx
pages/guides/integrations/with-framer.mdx
pages/guides/integrations/with-hook-form.mdx

Fixes for wrong language identifiers on code blocks for examples (only searched for jsx and tsx).
Also some small cleanups for the imports in the regarding examples.
Code block language identifier for jsx and tsx are inaccurate.
Code block language identifier for jsx and tsx are accurate.
No
Thanks @aaarichter for finding that issue on https://github.com/chakra-ui/chakra-ui-docs/pull/295

docs: fix code block language identifiers, cleanup imports in examples

---

pages/index.tsx

Closes #265 
On the landing page are a few company logos and user profile pictures which look and feels like links e.g. with `cursor: pointer`. At the following sections/heading:
- 'Supported and Backed by'-companies
- Chakra Heroes
- Individual Sponsors
Company logos / profile pictures on the landing page seems to be links but they are not.
Company logos / profile pictures on the landing page are links.
No
Used the Chakra UI Link component to have the native link feeling. Could theoretically also be done by adding an `as='a'` prop. Tried to avoid that because in my mind it is not good to also provide link props into the ChakraNextImage and on the other hand it is bad practice to overwrite `li` tags, like on this changes in this PR.

docs: add missing links on landing page

---

pages/docs/contributing.mdx

Closes #281 
The Contributing guide was outdated and wasn't refreshed since we've moved the docsite into its own repo.
The Contributing guide has old and outdated steps.
The Contributing guide is refreshed and explains how to get started with contributing on both the Chakra UI and docsite repos.
No

docs(contributing): updating contributing guide

---

pages/index.tsx

The 'Your company' Box on the 'supported and backed by' section has a different width and height than the company link list items. The placeholder is also a div in an unordered list.
- Box has wrong width and height, which resulted in an alignment issue of the hole unordered list.
- div inside the unordered list
- alignment of list items in the unordered list is fixed
- only list items in the unordered list 
- 'Your company' is now a link to the [membership plans](https://opencollective.com/chakra-ui/contribute), should be much easier to find for companies now. :money_with_wings: 
No

fix: size of 'your company' box

---

pages/docs/features/responsive-styles.mdx

Closes #219 
The "Under the Hood" example in the Responsive Styles page has wrong values.
The example shows `40em` and `52em` for the `sm` and `md` breakpoints.
The example shows `30em` and `48em` for the `sm` and `md` breakpoints.
No

docs(responsive-styles): fixed example typo

---

pages/docs/features/style-props.mdx

Closes #319 
Update filter props section of the "Style Props" pages to have live output of the example code, along with correction theme field cell of the props tables and notation on the lack of support in Firefox for the `backdrop-filter` property.
Documentation for the filter properties does not have live examples and editable code
Enable live output of the example code, with updated styling and colored images to better demonstrate the filter types provided in the examples.
No

docs(style-props): Make Filter examples live and editable.

---

pages/docs/overlay/modal.mdx

Closes #307 
Adding a section for styling the backdrop on modals.
No information about and examples for styling the backdrop.
Information about styling the backdrop with two editable examples.
Hint for browser compatibility.
Example 1 with blur and hue-rotate filters in the backdropFilter property:
Example 2 with invert and blur filters in separated props and the backdropFilter set to 'auto':
No.

docs: add backdrop style section for modals

---

pages/docs/form/checkbox.mdx

The `defaultIsChecked` attribute is now marked deprecated and replaced with `defaultChecked` - the documented component examples should reflect this.
`defaultisChecked` usage remains throughout:
https://chakra-ui.com/docs/form/checkbox
Examples now use the supported attribute instead.
No
Nil

docs(checkbox): Replace deprecated defaultIsChecked attribute

---

pages/docs/overlay/tooltip.mdx
pages/faqs/index.mdx

Closes #302 
Add an entry on the faq page and a section on the Tooltip page for Tooltips around disabled Buttons.
No informations about Tooltips around disabled Buttons.
Informations on faq page and a section on the Tooltip page.
No.
Thanks for asking/reporting and the codesandboxes to @DeeeeLAN on https://github.com/chakra-ui/chakra-ui/issues/5528 and @raulrpearson on https://github.com/chakra-ui/chakra-ui/issues/2849. :rocket:

docs: faq and section for tooltip around disabled button

---

pages/docs/navigation/breadcrumb.mdx

Closes #138
Added a section for having a BreadcrumbSeparator on the last item of the Breadcrumb component.
No information for using the separator as last Breadcrumb item.
New section for using the separator as last Breadcrumb item. Also creation of clean HTML was taken into account.
No.
Thanks to @primos63 for the informations in https://github.com/chakra-ui/chakra-ui-docs/issues/138#issuecomment-990724557

docs(breadcrumb): add section for separator in last item

---

scripts/get-showcase-data.ts

Closes https://github.com/chakra-ui/chakra-ui-docs/issues/317
Escapes characters that cannot be used on Windows.
name: Choosing the right component library for your design system: MUI vs Chakra
generated file: Choosing-the-right-component-library-for-your-design-system:-MUI-vs-Chakra.png
`:` is not available in the Windows file system.
`<` `>` `"` `/` `¥` `|` `?` `*` is another character that cannot be used.
name: Choosing the right component library for your design system: MUI vs Chakra
generated file: Choosing-the-right-component-library-for-your-design-system--MUI-vs-Chakra.png
No
The commit also contains formatting fixes.

Fix showcase generation script special character issue

---

src/components/omni-search.tsx

Closes #348 
This adds a check if the results of the search are empty. If so then the 'Enter' event doesn't do anything. If not then it behaves as before.
When search results are empty an error is thrown because we try to look something up in an empty array.
Checks if the results array is empty before looking up the page to redirect to. Ignore the lookup if the array is empty.
No

fix: improved handling for empty search results

---

src/components/framework-link.tsx
src/components/framework-svg.tsx

Closes #359
Sets the color of the Remix SVG to black and fixes the overlapping of FrameworkLinks bgColor in the bottom corners in dark mode.
- invisible color of Remix SVG due to fill set to currentColor
- overlapping pixels of the bgColor in the bottom corners
- color of Remix SVG is set to black, similar to the Next.js SVG
- no white bgColor visible in the bottom corners by increasing the borderRadius
No

fix: remix icon color and overlapping bgColor in framework link in dark mode

---

pages/docs/features/global-styles.mdx

Closes #369 
Remove the whole community example section of the global styles page because the only link within is broken.
Constains only one link, which is broken.
Remove the whole section.
No.

docs: remove global styles community examples section

---

next.config.js

Removes the `target` entry in `next.config.js` as it is [deprecated](https://nextjs.org/docs/messages/deprecated-target-config).
Warnings appear in builds and development:
```
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
```
Warning no longer logged.
No

chore: Remove depreciated deployment target in next.config.js

---

pages/resources.tsx

Removed `target=_'blank'` on the showcase banner within the resources page. Also wrapped the LinkOverlay with `NextLink` because the showcase is an internal site.
Showcase banner is a simple link with `target=_'blank'`.
Showcase banner is a NextLink without `target=_'blank'`.
No

fix: remove target blank on showcase banner

---

pages/changelog/content.mdx

Currently, there is an error in the grid example, as a result of incorrect closing tags
Grid has incorrect closing tags
Grid closing tags are now correct
No

fix: Grid example closing tags

---

pages/guides/getting-started/nextjs-guide.mdx

Closes #387 
Adding a `ColorModeScript` section in the Next.js guide.
No `ColorModeScript`.
Added the `ColorModeScript` section, plus did a little content cleanup.
No

docs(nextjs): Adding ColorModeScript in Next.js Guide

---

pages/docs/styled-system/features/style-props.mdx

Closes # https://github.com/chakra-ui/chakra-ui/issues/561
- add missing `content` property & example for `::before` example with extra note about quotes
- content prop is missing and no clear example for its usage
- add missing `content` property & example for `::before` example with extra note about quotes
no

fix(style-props): add content property and example to style-props page

---

src/components/features-overview.tsx
src/components/sidebar/sidebar-link.tsx

Closes #395 
This adds a scroll the sidebar when the user comes from the component / styled-system overviews. Like this the user sees where he actually is on the sidebard. The scroll event is not triggered when the user uses the sidebar normally.
Sidebar is not scrolling as described in the issue. Kinda confusing for the user.
Sidebar now scrolls.
No
I chose to trigger the scroll event with a flag in the url as it only has to be triggered conditionally and from outside of the actual component where the event is triggered.

feat: scroll sidebar when coming from overview

---

pages/docs/components/recipes/floating-labels.mdx

Closes #379 
The given recipe for floating labels behaved differently based on the floating label length.
Using transformOrigin the floating label will always positioned the same.
No

Ensure float label recipe behaves independently from label length

---

pages/docs/components/form/number-input.mdx

Closes #402 
Adding a short hint in the `NumberInputField` Props section about changing the size.
The current documentation says that the `NumberInputField` composes `Input` so we can pass all `Input` props. This means that if we want to change the size we can set the `size` prop to the `NumberInputField` component, which is wrong in this case. To change the size we need to pass the `size` prop to the `NumberInput` component instead.
I've added an additional hint in the "NumberInputField Props" section at the bottom regarding the size.
No

docs(numberinput): added NumberInputField size hint.

---

pages/docs/components/overlay/alert-dialog.mdx

Use the useDisclosure hook in first AlertDialog examle instead of useState.
The current first example for the Alert Dialog uses useState to determine whether the component should be visible or not. All other examples use the custom useDisclosure hook.
The first example now uses the useDisclosure hook, too.
No

docs: use useDisclosure in alert AlertDialog example

---

pages/guides/getting-started/remix-guide.mdx

Closes N/A (no existing issue)
This PR fixes the imports in the Remix Getting Started guide.
As far as I know, the `... as React` is used when we import all named exports using `*`, e.g.:
```ts
import * as React from 'react';
```
Instead, here, previously what we did was:
```ts
import React, { createContext } as React from "react"
```
This causes syntax errors in the IDE. In the later sections, we can see that the imports are specified differently than the ones above (which I think, this is the correct one).
```ts
// root.tsx
import React, { useContext, useEffect } from 'react';
```
1. Remove the `as React` part of the line of code
2. Small update: use a single quote instead of double (to make it consistent with the later sections).
No
If the previous one's syntax was valid, please let me …

docs: fix Getting Started > Remix `react` imports

---

configs/search-meta.json
pages/changelog/index.mdx
scripts/get-changelog.ts

The Changelog search meta URL was pointing to `/changelog/content` because the changelog contents were kept in the `content.mdx` file. I renamed the `content.mdx` to `index.mdx` to avoid the `/content` segment when generating the search meta.
The Changelog entry in the Search is pointing to `/changelog/content`, and it goes to the 404 page.
The Changelog entry now points to just `/changelog` and no 404 happens.
No

fix(changelog): fixed changelog search meta url

---

pages/docs/styled-system/features/style-props.mdx

Closes https://github.com/chakra-ui/chakra-ui-docs/issues/433
Add missing paddingY, paddingX, marginY and marginX style properties to the dedicated margin/padding table in style properties documentation page
No

docs(style-props): add missing paddingY, paddingX, marginY and marginX style properties

---

scripts/get-search-meta.ts

Closes #438 
On Windows 10, running `yarn search-meta:gen` script to generate an updated `search-meta.json` file will render the local directory path in the `url` property. This request wraps the `fileToPath` function around `process.cwd()` when trimming the slug to ensure the same slash characters in the filepath from the string passed through the `file` param of `getMDXMeta` and the current working directory string from node process.
Running `yarn search-meta:gen` renders in the `url` property the full local directory path in Windows 10...
i.e. `C:/Users/user/path/to/file/<page>`
where the meta file string passed to the `getMDXMeta` function contains forward slash characters, and `process.cwd()` returns a local directory path containing back slash characters.
Passing `process.cwd()` to …

fix(get-search-meta): fix bug where local directory path is not being removed from url property in Windows 10

---

pages/docs/styled-system/features/responsive-styles.mdx
pages/docs/styled-system/theming/theme.mdx
pages/guides/migration.mdx

- Removes the `createBreakpoints` function from the docs due to deprecation, like described in [create-breakpoints.ts](https://github.com/chakra-ui/chakra-ui/blob/8e201b9f84a914e58cdc9ee90b3e03269fabf4d7/packages/theme-tools/src/create-breakpoints.ts#L20)
- Adds imports and hints for usage on the default theme page
usage of deprecated function in the docs
removed deprecated function
No

docs: remove deprecated createBreakpoints function

---

pages/guides/getting-started/remix-guide.mdx

fix typo in `pages/guides/getting-started/remix-guide.mdx`

docs: fix typo in remix template

---

pages/docs/components/navigation/link-overlay.mdx

Closes #473 
Removing the "View Theme Source" link from [Link Overlay](https://chakra-ui.com/docs/components/navigation/link-overlay) page.
"View Theme Source" 404s.
Removed "View Theme Source" button because the LinkOverlay does not have a theme source.
No

docs(link-overlay): remove view theme source link

---

pages/docs/components/form/button.mdx

fix typo in `pages/docs/components/form/button.mdx`

docs: fix typo in grouping buttons

---

pages/docs/components/layout/stack.mdx

Closes #465 
This PR improves two sections of the Stack documentation. 
- The examples for horizontally stacking items.
- The section Flex vs Stack
Currently the above mention sections are contradictory and unclear.
I've made sure to clear things up by providing more examples and updating the section regarding the difference between Flex & Stack.
No.

docs(stack): Update Stack documentation

---

src/components/mdx-components/codeblock/react-live-block.tsx

`overflowX: auto` and `whiteSpace: pre` are applied to the `LiveCodePreview` component to constrain the live code examples within the preview container, allow for horizontal scroll, and preserve the intended white space from the example.
Some current live previews are overflowing the preview container when viewed in a mobile device, breaking the page layout.
Hide the overflow and allow for horizontal scrolling with `overflowX: auto` applied to the `LiveCodePreview` component.
Also apply `whiteSpace: pre` to preserve white space of any text content and prevent the text from getting compressed, depending on the created code example.
No
This PR provides a simpler, more global, and less confusing fix than PR #488.

fix(react-live-block): allow horizontal scroll of preview in mobile screens

---

pages/docs/components/form/number-input.mdx

TypeScript throws errors if we use `isReadOnly: true` in the `getInputProps()` function. Although, if we pass `isReadOnly` does work, there seems to be a type error. However, when using `getInputProps({ readOnly: true });` both TypeScript and functionalities work. So, there is not a change. You just have a stricter type system.
Maybe, change the initial types of the `getInputProps()` parameters?
Closes # 

Update number-index.mdx | TypeScript throws error

---

pages/docs/components/layout/container.mdx

Closes Issue #401
Moves the details about `maxWidth` to the section [Container Size](http://localhost:3000/docs/components/layout/container#container-size) and update the description and examples
- The detail about the default `maxWidth` sits at the top of the page away from the size section
- The container size live code example has no color to be able to easily visualize the different maxWidth values rendered to the `Container` components.
- Per discussion in issue #401, there is no explanation on the page given about the default value of `60ch`. Not everyone knows about this unit value or knows why this particular value might be used. (This is related to UX/UI best/suggested practice)
- The details about the default `maxWidth` are moved to the sizes section and updated to include notes …

docs(container): update "Container Size" section

---

configs/guides-sidebar.json
pages/guides/getting-started/redwoodjs-guide.mdx

Refers to https://github.com/chakra-ui/chakra-ui/discussions/5785
Closes #499 
This updates the RedwoodJS integration tutorial to state of the art – in order to 
rectify / avoid any confusion that may arise when comparing the integration 
tutorial with the way RedwoodJS integrates Chakra UI out-of-the-box. 
The current doc seems out outdated. @TimKolberger themself [contributed a
script](https://github.com/redwoodjs/redwood/pull/3715) to RedwoodJS that 
creates a component structure a little different from what the tutorial advises.
This PR synchronizes the doc with the way RedwoodJS sets up projects for 
ChakraUI. Also added a reference to the console command to achieve that.
No.
https://github.com/chakra-ui/chakra-ui/discussions/5785
Maintainers, pls feels free to fixup or amend my …

Update RedwoodJS integration tutorial

---

.github/workflows/release.yml

Closes # /
Sibling PR to review: 
https://github.com/chakra-ui/chakra-ui/pull/5834
The issue was if we are running multiple yarn commands, we should add a pipe (|) instead of slash (/)
The github action failed.
The github action is actually fixed and will bump the Chakra version.
No.

fix: adding pipe for bumping chakra ui versions

---

src/components/mdx-components/codeblock/react-live-block.tsx

Closes #505 
With the merge of PR #496 the intended purpose of including `whiteSpace: pre` with the addition of `overflowX: auto` in the `LiveCodePreview` component was to retain white-space when horizontal scroll occurs in live code example previews, so text content was not compressed. Unfortunately, an overlooked side effect is other previously unaffected examples forcing text content out of view with no ability to scroll, or creating new overflow. This PR simply removes the `whiteSpace` prop
Examples like those in the [`Alert` docs](https://chakra-ui.com/docs/components/feedback/alert) have text content forced out of view in the preview window and no ability for horizontal scroll.
Examples like the [`Popover` basic usage](https://chakra-ui.com/docs/components/feedback/alert) have text …

fix(react-live-block): remove `whiteSpace: pre` from `LiveCodePreview` baseStyle

---

pages/guides/getting-started/remix-guide.mdx

- Update the case to use the latest remix.
- There is no module named "remix". Use @remix-run/xxx instead.
- The use of `LiveReload` does not require conditional branching in the environment.
- meta tags and link tags are defined with the meta and links functions.
- Import of some modules was missing.
- Semicolon and quotation rules were not consistent.

docs: update the current version of the remix

---

pages/docs/components/feedback/alert.mdx

Closes #522 
On certain smaller mobile screens, the content within the live example code of the [Usage]() section overlaps the close button due to the close button being absolutely positioned and no other adjustment to wrap the text before reaching this component.
Along with this, it is not considered "basic usage" of the `Alert` component to have a close button that is not a part of the component package.
Therefore, this PR simply removes the `CloseButton` component.
At certain mobile screen sizes roughly 500px and below, the content from `AlertDescription` overlaps the `CloseButton` component.
`CloseButton` component is removed and the `AlertDescription` component behaves as normal.

fix(alert): remove `CloseButton` component from basic usage example

---

src/components/algolia-search.tsx

This PR updates the color contrast in the `AlgoliaSearch` button component so all text content is WCAG compliant.
The `color` prop is removed from the `Kbd` components that render `Crtl` and `K` text.
The `color` prop in the parent button receives a `useColorModeValue` value of either `gray.600` or `gray.400` which comply with light and dark mode contrast respectively and pass it's value down to the children.
In dark mode, the `Crtl` and `K` textual inputs fail accessibility with a contrast ratio of 2.99.
In light mode, all text and the search icon fail accessibility with contrast ratios of 2.26 to 3.56.
In dark mode, all text pass accessibility with a contrast ratio of 5.32.
In light mode, all text pass accessibility with contrast ratios of 6.68 to 7.53.
_This partially addresses issue …

fix(algolia-search): adjust color contrast to search button

---

configs/sandpack-contents/framer-motion-examples/chakra-factory.js
pages/guides/integrations/with-framer.mdx

Closes #541
This is an update to the Chakra Factory example for [Chakra + Framer](https://chakra-ui.com/guides/integrations/with-framer#usage), where it shows the inclusion of the `children` prop in `shouldForwardProps`
Currently, `shouldForwardProp` only passes in `isValidMotionProp` so that the Framer animations are active and not overridden by matching props from Chakra. However, you can't use child components because the `children` props ends up being ignored, despite all other chakra props still available for use. This is not notated for users to be aware of.
The inclusion of forwarding the `children` prop in `shouldForwardProps` is provided in the example with a comment underneath. All other chakra props not matching the motion props can still be used.
The overall example is updated …

fix(with-framer): update factory example and details

---

pages/guides/getting-started/remix-guide.mdx

Closes # 
> Fixed import of RemixServer component location
> Receiving following error when setting chakra up to remix:
`Error: Cannot find module '@remix-run/server'`
> Avoids users to have an error when setting up chakra-ui with Remix

docs: changed remix server import location

---

pages/docs/components/feedback/toast.mdx

Use a `Wrap` component instead of `Stack` surrounding the buttons in the "Closing Toasts" section example so the button text never compresses and allow the buttons to stack in mobile view, down to `375px` screen width
The buttons in the "Closing Toasts" example stay inline via `Stack` and it's `isInline` prop wrapping the buttons, which compress the button text when shown on a mobile device.
Replace `Stack` with `Wrap` and no props to allow the text content to not overflow the button and allow the buttons to stack when the width of the container is too small.

fix(toast): replace `Stack` parent component with `Wrap` in "Closing Toasts" example

---

pages/docs/components/overlay/menu.mdx

Update details of the "Customizing the button" section of the `Menu` docs to reference the Chakra `forwardRef` function.
Current documentation mentions that a `ref` is needed to be supplied to a custom component when using it in the `MenuButton` so that the styling of the popover is maintained. But to a new user of Chakra, they may not necessarily know how to do that in the context of Chakra.
Reword the details to provide the suggestion of creating the custom component using `forwardRef` as a way to supply the `ref`, along with allowing the custom component to be flexible within Chakra.

docs(menu): update "Customizing the button" section and add link to `forwardRef`

---

pages/docs/components/overlay/drawer.mdx

Improve usability of the "Drawer Widths" section code example by providing the ability to toggle the drawer closed via a close button.
There is no close button rendered for the different size drawers. This diminishes UX of the example on mobile with the drawers that cover the entire screen, as they force the user to refresh the page to close them.
Add close button for each rendered drawer. Also tweak the overall presentation of the example.

docs(drawer): update usability in size code example for mobile

---

pages/docs/styled-system/utility-hooks/use-disclosure.mdx

Closes #563 
Add documentation for the getter methods returned in the `useDisclosure` hook, and update the rest of the docs for better accuracy of overall usage of the hook.
Documentation only provides examples of the functions and boolean value returned by the hook
Adds the getter methods with their own example, showing their usage as the most basic with the hook. Updates the original example by providing detail on how the other methods and boolean value returned from the hook are used to provide more control.
Until the docsite dependencies are bumped, the `getButtonProps` will still return a static `aria-expanded` value if the user inspects the example button via devtools. Fixed in PR [#5940](https://github.com/chakra-ui/chakra-ui/pull/5940).

docs(use-disclosure): create details for the getter methods

---

pages/changelog/index.mdx

JSX examples from the most recent changelogs in the [Changelog](https://chakra-ui.com/changelog) doc page are attempting to render preview, and end up breaking with visible error messages on the page.
Added `live=false` to these examples in the `changelog/index.mdx` file.

fix(changelog): turn off live previews to affected jsx examples

---

pages/docs/components/overlay/popover.mdx

Closes #513 
Add details in the [Basic Usage](https://chakra-ui.com/docs/components/overlay/popover#basic-usage) and [Popover Anchor](https://chakra-ui.com/docs/components/overlay/popover#popover-anchor) sections about using Chakra's `forwardRef` in custom components that are used as children in `PopoverAnchor` and `PopoverTrigger`.

docs(popover): mention `forwardRef` with custom components

---

configs/sandpack-contents/advanced-formik-integration/image-radio-buttons.js
configs/sandpack-contents/floating-labels/floating-labels.js
configs/sandpack-contents/formik-examples/login-form.js
configs/sandpack-contents/formik-examples/plain-formik.js
configs/sandpack-contents/formik-examples/simple.js
configs/sandpack-contents/formik-examples/validation.js
configs/sandpack-contents/framer-motion-examples/as-props.js
configs/sandpack-contents/framer-motion-examples/chakra-factory.js
configs/sandpack-contents/homepage/files.ts
configs/sandpack-contents/prose/prose.js
pages/docs/components/recipes/floating-labels.mdx

Update all Sandpack code examples in the docsite with the following changes:
- Convert code to React 18 API
- At least one example has its code inline in the `files` prop of the `SandPackEmbed` component. Move this code to the `sandpack-content` directory to de-clutter the doc file and provide consistency with other sandpack content.
- Only addresses typing error related to ChakraUI Issue [#6023](https://github.com/chakra-ui/chakra-ui/issues/6023) as it is a quick fix. Other typing errors in the example should be addressed in a separate PR, if need be. (Example may need a revamp, typescript-wise?)
(VERY MINOR) Per the React 18 Concurrent Renderer, because the generated files in the `SandPackEmbed`s are `.tsx`, the container passed to `createRoot` needs a postfix to prevent an "is null" …

docs: update sandpack examples

---

pages/docs/components/form/slider.mdx

Update the slider example with the custom floating mark to ensure everything is visible in the live preview container.
Due to the live preview having `overflowX: auto`, the floating mark in it's absolute positioning is clipped out of view.
To maintain integrity of the example, provide a wrapper `Box` component that sets padding to bring the floating mark into view.
This PR also tidies up the example with a small refactor.

fix(slider): update the first "Slider with custom labels and marks" example

---

pages/docs/styled-system/recipes/using-fonts.mdx

The existing examples for the [Using Fonts](https://chakra-ui.com/docs/styled-system/recipes/using-fonts) recipe incorrectly reference font families for the theme. If you don't wrap the font family with quotation marks, it will fail to load if the font name has any whitespace between it, which is the case for the Open Sans example.
While it's okay to not wrap quotation marks around font names like Inter, for the sake of reducing future confusion on why some fonts work and others may not due to this niche CSS rule, I think it's best to wrap every example with quotation markers.
This PR updates the examples with valid examples. Using backticks, escape backslashes or double quotes is purely preferential. I personally chose backticks because I think it looks the cleanest.
[MDN …

docs: correct font theme examples

---

pages/docs/components/overlay/popover.mdx

In the `Popover` component docs, in the "Controlled State" example, replace `useState` with `useDisclosure`.
Used the `useState` hook.
Uses the `useDisclosure` hook.
No

docs(popover): use `useDisclosure` in controlled state example

---

src/components/mdx-components/component-links.tsx

Closes #619
Revert the `overflow` prop originally set from the `Wrap` component that contains the component links (i.e. source code, theme, npm) to allow the boxShadow on focus and the transition on hover to not be clipped.
Clipping comes from the combination of `overflow: hidden` and negative margins, both set by the `Wrap` component.

fix(component-links): allow overflow of the container

---

pages/guides/getting-started/remix-guide.mdx

The preconnect link for google fonts in the Remix guide has a typo. This change corrects the incorrect url

docs: use correct google font preconnect link

---

pages/docs/components/form/checkbox.mdx
pages/docs/components/typography/heading.mdx

Closes #667 and #669
Extension of documentation for breakpoints on the fontSize of `Heading` by using the `size` prop.
No

docs: extend doc for size prop of heading

---

pages/index.tsx

No issue opened
This fixes an inconsistency the repeating audio bar graphic on the talk invite section on the homepage.
No
- https://caniuse.com/background-repeat-round-space

bugfix: Use background repeat space on talk invite graphic

---

pages/docs/components/overlay/modal.mdx

When i use modal examples(like InitialFocus), i get this type error.
`Type 'MutableRefObject<undefined>' is not assignable to type 'LegacyRef<HTMLButtonElement> | undefined'.
Type 'MutableRefObject<undefined>' is not assignable to type 'RefObject<HTMLButtonElement>'.
Types of property 'current' are incompatible.
Type 'undefined' is not assignable to type 'HTMLButtonElement | null'.ts(2322)
index.d.ts(137, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, keyof ButtonProps> & ButtonProps & { ...; }'
`
To fix this error, i add null for initialValue
Type incompatible error occurs
The error disappear

docs: add initialValue to fix a type error of ref

---

src/components/sidebar/sidebar-link.tsx

When you open a hashed URL and navigate through the pages, the URL you opened remains active. I modified the conditions the link is active in sidebar.
1. Open URL with hash https://chakra-ui.com/guides/first-steps#framework-guide
2. Click other link in page
3. You can see 'First Step' is still active
1. Open URL with hash https://chakra-ui.com/guides/first-steps#framework-guide
2. Click other link in page
3. You can see 'First Step' is not active.
No

fix: fix active condition in sidebar link

---

pages/docs/styled-system/features/style-props.mdx

In the Styled System docs, beneath the `pseudo` section, there was a stray table row with the word `none`. This PR removes that stray word and row.
In the Styled System docs, beneath the `pseudo` section, an unnecessary row is shown with only the word `none`.
This PR removes that unnecessary row and the word `none`.
No.

Docs: Remove Stary Instance of 'none' in Pseudo Docs

---

pages/docs/styled-system/theming/theme.mdx

> Update broken link of [Styled system theme specification](https://system-ui.com/theme/) to [active link](https://styled-system.com/theme-specification/)
> Update broken link
> By opening [Styled system theme specification](https://system-ui.com/theme/) link on [Default Theme - Chakra UI](https://chakra-ui.com/docs/styled-system/theming/theme) it will open to a active valid link
No

docs: update styled system theme specification broken link

---

configs/site-config.ts
contentlayer.config.ts
i18n/ui.json
src/components/edit-page-button.tsx

Add a link to the end of each page (except changelog) to edit the page on GitHub.
No link from document page to directly edit it
Link added to the end of each page to provide easy way to access and edit the documentation
No

feat: add 'Edit this page on GitHub' link

---

configs/components-sidebar.ts

Closes nothing
This fix reorders the links of the components as presented in the docs.
When navigating from MEDIA AND ICONS section, from the Image component to the next component, you get to Transition, which isn't the first component in the OTHER section.
so the current NEXT order is:
Image-> Transitions -> Portal -> Show/Hide -> Close Button
Fix the order to be sequential.
new NEXT order is:
Image -> Close Button -> Portal -> Show/Hide -> Transitions
Just like in the visual presented order
NO
NO

fix(componenet-sidebar): change the order of items as it appears

---

content/getting-started/with-capsize.mdx

Closes #733 
Adds a notice to the [Chakra UI + Capsize](https://chakra-ui/getting-started/with-capsize) doc page stating that `@ceteio/chakra-capsize` is not up-to-date and not compatible with Chakra UI v2 and React 18.

docs(with-capsize): add outdated notice

---

content/docs/components/stack/usage.mdx

> Fixed Typo
> Docs state that HStack stacks elements in vertical direction.
> Changed it to state that HStack stacks elements in the horizontal direction.
No

Docs: Fix typo "vertical" -> "horizontal"

---

content/getting-started/index.mdx

Closes #751 
The code sample on the Getting Started page will cause an infinite loop if used directly. The App function definition will be called recursively.
New code sample does not call the App function recursively.

Update Getting Started page to remove potential infinite loop

---

layouts/component.tsx
next-redirect.js

Closes #747
There are still some missing redirects that result in 404s.
Missing redirects that cause 404s.
No more 404s!
Nope

fix(redirects): added missing redirects

---

layouts/blog.tsx

> Add in sidebar links for individual blog posts
When a user clicks a blog posts, they don't have a way to return to the site 
Add in sidebar so users can navigate to other parts of the site from the blog
No
N/A

feat: add sidebar to blogposts

---

scripts/get-showcase-data.ts

Closes #763 
Add missing pushes to the `showcase.json` of target items from `awesome-chakra-ui` repo that are from Github or Youtube.
There is a nested for loop in the `main()` function that loops through each item from `awesome-chakra-ui` to obtain an image path to be pushed to `showcase.json`. However, with the checks for Github and Youtube URLs that are true, image paths are retrieved but the entire item never gets pushed and the check gets hit with the `continue` keyword to immediately terminate and move to the next iteration of the loop. 
This PR simply adds the array push for any item that has a Youtube or Github URL.
_P.S. This will currently retrieve 10 items that were getting ignored in the script._

fix(get-showcase-data): add missing new data pushes

---

content/getting-started/comparison.mdx

Tailwind dark mode is [enabled by default](https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration) from Tailwind v3 onwards. They use the new JIT compiler so file size is no longer a concern.
Docs mention that tailwind dark mode needs to be explicitly enabled
Removed the part where the docs mention that tailwind dark mode needs to be explicitly enabled as this is no longer the case
No
None

fix(docs): update tailwind dark mode information

---

content/docs/components/popover/usage.mdx

Closes #773 
Replace broken props link in [Popover Placements](https://chakra-ui.com/docs/components/popover#popover-placements) section with list of values for the `placement` prop.
Note: Had to get a little creative to display the values neatly. They can't be supplied to the props table because it would require replacing a complex type signature with the explicit list of values in the Chakra package, which is no bueno.

docs(popover): add list of values for popover placements

---

content/docs/styled-system/advanced-theming.mdx

Fixed a broken link in the [advanced theming page](https://chakra-ui.com/docs/styled-system/advanced-theming)
Currently the link 404s
The link goes to the respective page, and to the respective section
No
None

docs: Fix broken link in advanced theming (for distributing theme packages)

---

content/docs/components/form-control/usage.mdx

- Little changes on some examples, removing unnecessary `htmlFor` and `id`;
- And improvements about usage of this properties at `Improvements from v1` section.
Today, the [documentation](https://chakra-ui.com/docs/components/form-control/usage) of `FormControl` shows `htmlFor` and `id` as necessary props (it doesn't say that, but it does imply)
Most samples will not show these props. However, their use is described for situations of greater need for control.
No

chore(FormControl): remove unnecessary htmlFor and id

---

content/getting-started/migration.mdx

This change just fixes a typo found on the docs seen here: https://chakra-ui.com/getting-started/migration#color-more-transition
`color more` -> `color mode`

Fix typo: color more -> color mode

---

content/docs/styled-system/style-props.mdx

Closes #853 
Remove the invalid prop `spacing` from the `Flex` parent components in the `filter` and `backdropFilter` code examples.

docs(style-props): remove invalid props from filter code examples

---

src/components/sandpack-embed/index.tsx

Closes #767 
All sandboxes have `latest` as version for the packages `@chakra-ui/react` and `@chakra-ui/icons` which caused problems on the **v1 docs**.
Most of the sandboxes in the **v1 docs** shows errors, see e.g. the example on the [startpage](https://v1.chakra-ui.com) or [Chakra UI + Formik](https://v1.chakra-ui.com/guides/integrations/with-formik).
This PR sets `@chakra-ui/react` and `@chakra-ui/icons` to the latest v1 version on the v1 branch.
No

fix: chakra ui version in sandboxes on v1 docs

---

content/docs/styled-system/advanced-theming.mdx

Closes # 
Fixed a broken link in the [advanced theming page](https://chakra-ui.com/docs/styled-system/advanced-theming)
The link 404s
The link goes to the respective page, and to the respective section
No
None

docs(advanced-theming): update link for theme typings

---

content/docs/components/number-input/usage.mdx

Closes #914
Adds a hint for the default `min` and `max` values.
No hints, information only on props tab (there it is currently wrong, PR is open, see below)
Adds a short hint for the default values of the `min` and `max` prop.
No
Fix for default values in docs: https://github.com/chakra-ui/chakra-ui/pull/6485

docs: add hint for default min and max prop of NumberInput

---

content/docs/hooks/use-checkbox-group.mdx
content/docs/hooks/use-checkbox.mdx

Closes # 
Fixed a problem in the `useCheckBox` demo where text was difficult to see in dark mode.
Added `color="gray.700"` to Text.
No
- Also modified `useCheckboxGroup`.
- Operation in Light mode has not changed.
- <img width="146" alt="image" src="https://user-images.githubusercontent.com/20895397/185913419-1eb2560b-93c4-41da-a764-25134dc90b4f.png">

fix(use-checkbox): fixed text color in dark mode

---

configs/sandpack-contents/floating-labels/floating-labels.js

Closes # 
>The current recipe documented does not support textarea's correctly
> Labels cover textarea when value is present 
> label floats when values are present
no

fix: floating label recipe to include textareas

---

content/docs/styled-system/customize-theme.mdx

Closes #945 
Customize Theme page contains a link that points to the old Foundations theme path.
Dead link.
No more dead link!
Nope

fix(docs): fixed broken link in customize page

---

content/getting-started/index.mdx

Fixes a small typo since presumably v1 is for React 17 or earlier, not later.
No

fix(docs): replace "later" with "earlier"

---

content/docs/styled-system/global-styles.mdx

There was a small English error on the chakra-ui global styles doc (it is missing the word "to")
It was missing the word "to" on the global styles doc.
Added the word "to" on the global styles doc.
No
Please let me know if I did anything wrong, I'm a first-time contributor to this repo. Thanks!

fix(docs): fix the small english mistake on the global-styles doc

---

content/docs/components/tabs/usage.mdx

> wanted to use the tabs component and noticed `React.useState()` was used instead of `useState()` one of the examples.
> syntax was `React.useState(0)`
> syntax was changed to `useState(0)`
NO

change React.useState(0) to useState(0)

---

content/getting-started/nextjs-guide.mdx

> Using a functional component over a class component is the recommended method to override the default document as per Next documentation: https://nextjs.org/docs/advanced-features/custom-document
> Docs for NextJS Custom Document use class component
> Docs for NextJS Custom Document use functional component
No

(docs) Next JS: Change custom document to use functional components.

---

content/docs/styled-system/component-style.mdx

This change updates the docs for creating custom themed components, so that it uses the same tools as Chakra does internally - namely the `defineStyleConfig` and `createMultiStyleConfigHelpers` functions.
No

Update docs with defineStyleConfig et al

---

.vscode/extensions.json

In the `.vscode/extension.json` the recommended MDX extension listed is now deprecated. This PR replaces it with the current extension
.

chore(.vscode): replace deprecated mdx extension

---

content/docs/hooks/use-breakpoint-value.mdx

Add the `live=false` flag to the code block for the last example in the [useBreakpointValue](https://chakra-ui.com/docs/hooks/use-breakpoint-value) doc page
With no `live=false` this example attempts to open a preview, but throws an error because of improper syntax. 
This example did not intend to have a preview and `live=false` removes the rendered preview window
Nope

Set `live=false` to final `useBreakpointValue` code example

---

content/docs/styled-system/component-style.mdx

the `defineStyleConfig` was being imported from the wrong place. I have made the change to the docs to import from `'@chakra-ui/react'` instead of `/theme`
No

docs: fix import statement to reflect where defineStyleConfig is

---

content/docs/components/form-control/usage.mdx

Closes #1066
PR #1030 introduced a change to the Formik code example in the [FormControl](https://chakra-ui.com/docs/components/form-control/usage#usage-with-form-libraries) component docs, where an import statement for `Formik` was added to define which components from that package are being used compared to components from Chakra.
However, based on how the React Preview is designed, import statements from packages do not need to be defined in the code block, and break in the compiler. Therefore, this import statement should've been added as a comment.
Preview of the Formik example does not render, and a syntax error is thrown
Import statement is commented out and the preview renders as expected
No

fix(form-control): comment out import line in Formik example

---

content/docs/components/tooltip/usage.mdx

Closes #1023 
After chakra-ui/chakra-ui#6653, the workaround is no longer necessary.
It's basically just a revert of https://github.com/chakra-ui/chakra-ui-docs/commit/2551661a1c820fdd8c40bfb128834283bd151883
This section is outdated.
This section is removed.
No

docs(tooltip): remove "Tooltip around disabled Button" section

---

configs/sandpack-contents/component-theming/link.js
content/docs/components/link/theming.mdx

Closes #1076 
Adds theming documentation for the `Link` component.
No

feature(docs): link component theming docs

---

content/docs/components/tabs/usage.mdx

Fixes a small English mistake in the [`Tabs` docs](https://chakra-ui.com/docs/components/tabs)
No

Fix a small grammar mistake in the Tabs docs

---

configs/sandpack-contents/component-theming/number-input.js
content/docs/components/number-input/theming.mdx

Closes #1078 
> The goal of this pull request is to add theming documentation for the Number Input component.
> Currently, there is no documentation on how you can theme / customize the Number Input component.
> Now, when the devs that use Chakra UI can find clear instructions on how to customize the Number Input.
No.

feature: Adding theming documentation for Number Input

---

configs/sandpack-contents/component-theming/tooltip.js
content/docs/components/tooltip/theming.mdx

Closes #1095 
Add `Tooltip` component theming docs and corresponding Sandpack.

feat(docs): add tooltip component theming docs

---

content/docs/hooks/use-clipboard.mdx

Adds the setValue field and an example using the new setValue action
> Now that `useClipboard` supports `setValue` we should update the docs to reflect the new functionality. https://github.com/chakra-ui/chakra-ui/pull/6763
No

docs: Update use-clipboard.mdx

---

content/getting-started/index.mdx

> Add `pnpm` installation in Installation page
No
These days a lot people are using `pnpm` as their package manager instead of `npm` or `yarn`.  This PR adds an instruction in Installation page. Basically the `pnpm` command have same command with `yarn`, but it will helps people that never using `yarn` / `npm` or new `pnpm` user easier to find the instruction directly.

feat: added `pnpm` installation

---

src/components/header.tsx

use `useScroll` instead of `useViewportScroll`, because `useViewportScroll` have been deprecated 
There is an error in the devtools.
```js
react_devtools_backend.js:4026 useViewportScroll is deprecated. Convert to useScroll().
```
clearn warn in the devtools
NO

chore: update deprecated api in framer-motion

---

src/components/version-switcher.tsx

Workaround for white version switcher. We should probably make a proper fix for Select's unstyled-variant overriding [`Select.baseStyle.field._dark`](https://github.com/chakra-ui/chakra-ui/blob/cbd09c3/packages/components/theme/src/components/select.ts#L22)
Closes https://discord.com/channels/660863154703695893/660863154703695896/1045820502586962030
> make version switcher apply the page background color to it's menu.
> In darkmode, the select menu and it's `<option>` items use white text on white background (in both Firefox and Chrome)
> In darkmode, it now shows white text on **dark background**
No
Screenshot of the old behavior (from the original bug report on Discord)

fix version-switcher in dark mode

---

content/docs/components/spinner/theming.mdx

Closes #1100 
Added docs for theming on the spinner component.
No previous theming docs.
Add docs for theming the spinner component.
No.

docs: add spinner component theming docs

---

content/getting-started/migration.mdx

the correct standard prop should be "wordBreak" ("wordWrap" doesn't exist)
Closes # 
when migrating chakra to v2, the "isTruncated" indicates to use "wordWrap" prop. 
This prop doesn't exist and leads to confusion.
n/a
n/a
n/a

docs(migration): update prop "wordBreak"

---

content/docs/components/icon/usage.mdx

The examples for the icon component in 2 places said `use the 'boxSize' prop to change the icon size` but the example given had `w` & `h` passed instead.
Closes # 

docs(icons): Update examples to use the suggested prop (boxSize)

---

content/docs/components/badge/theming.mdx

Active implementation defines style as "boxy" but references "outline" variable in a code block. This PR aligns the variable names within that code block.
Closes # 
Active implementation defines style as "boxy" but references "outline" variable in a code block. This PR aligns the variable names within that code block.
Variable "boxy" is defined as a style, but variable "outline" is referenced within styleConfig.
Variable "outline" is changed to "boxy."
No.

chore: aligning variable names for consistency

---

content/docs/components/card/usage.mdx

Fix minor typo in the documentation of the card component
n/a
no new behavior

docs(card): add missing double quote and fix styling for prop name

---

pages/index.tsx
src/components/sandpack-embed/index.tsx

Closes #1210 
The preview of the CodeSandbox on the landing page went over the header.
As mentioned above, the preview went over the header, causing the header to look behind the preview.
I've added a zIndex of 0 to the preview on the landing page and extended the previewOptions to accept `BoxProps`.
No.

bugfix: Preview going over header 

---

configs/sandpack-contents/formik-examples/validation.js

> Length adjusted from password input validation
> The validation checks if password is less than five 
> The validation checks if password is less than six
> No

fix: Adjust length of password input validation

---

src/components/page-container.tsx
src/utils/contentlayer-utils.ts

Closes #817
The table of contents didn't update when we switched tabs, I have updated the `contentlayer-utils` to make that possible.
Currently, when switching from the `Usage` to the `Theming` tab, the table of contents doesn't update.
Now it will update as it gets the proper headings on the site.
No.

bugfix: Table of Contents didn't update when you switched tabs

---

content/docs/components/card/theming.mdx

Just a little error in the card theming doc page. It actually worked, but typescript complained a lot. `definePartsStyle()` was just in the wrong place in the object. The "custom size" section below it has the correct setup.

Small typescript error in card theming docs

---

src/components/props-table.tsx

Hello, first time contributor here 😄
Fixes boolean default value display in props table.
`true` default value in props table show an empty string, `false` as a default value hide whole default value line, because of a falsy condition in `src/components/props-table.tsx` :
```typescript
{prop.defaultValue && (
<Flex>
<div className='row'>{t('component.props-table.default')}</div>
<div className='cell'>
<InlineCode whiteSpace='normal' fontSize='0.8em'>
{prop.defaultValue}
</InlineCode>
</div>
</Flex>
)}
```
Sometimes `false` is already in string in json docs files, in this case nothing changes because the type is a string not a boolean, for example :
```json
"allowPinchZoom": {
"type": "boolean;",
"defaultValue": "false.", // instead of literal value `false`
"required": false,
"description": …
```

docs(props-table): fix boolean default value display in props table

---

src/components/omni-search.tsx

Small fix to use a unique key in Omni Search results.
Omni Search use `item.id` from `configs/search-meta.json` as a key for search results which is not unique. It results in outdated data (unordered search results, unhoverable... check video as an example) and poor performance because React can't optimize rendering correctly.
Example of non-unique id :
Video of outdated data :
https://user-images.githubusercontent.com/56580353/216851993-58a7fccb-c839-42bf-9551-67643757bc45.mp4
Use `item.url` which is unique across all search data entries which results in correct search results 😄
No.
Not needed.

docs(omni-search): fix non-unique key in omni search results

---

pages/guides/getting-started/nextjs-guide.mdx

Closes #1402
Both npm and yarn commands install the v1 version of chakra-ui in the NextJS docs
Only changes to v1 docs
Now the package installed for ```@chakra-ui/react``` is up to the version the docs are written for (v1) for users that are getting started with the v1 version
No

Updated package version to v1 in NextJS getting started docs

---

content/docs/styled-system/responsive-styles.mdx

Closes # 
> Added Em to PX conversion comments, so that it will be easier to understand in pixels
> Current presentation has no em to px conversion comments. So I added it
```js
const breakpoints = {
sm: '30em',
md: '48em',
lg: '62em',
xl: '80em',
'2xl': '96em',
}
```
```js
const breakpoints = {
sm: '30em', // 480px
md: '48em', // 768px
lg: '62em', // 992px
xl: '80em', // 1280px
'2xl': '96em', // 1536px
}
```
NO

Added Em to Px conversion comments, for better understanding.

---

content/docs/components/transitions/usage.mdx

Closes #1307 
The **Collapse** component is missing some information on the **Transitions** page. It is not listed in the imports example and it is also not included in the description of Transitions.
Missing **Collapse** information in **Transitions** page.
List the **Collapse** component in imports example and in **Transitions** description.
No.

docs: added collapse info in transitions page

---

configs/sandpack-contents/advanced-formik-integration/image-radio-buttons.js
content/docs/components/radio/usage.mdx
content/docs/hooks/use-radio-group.mdx
content/docs/hooks/use-radio.mdx

Closes #1515 
Updated custom radio docs [#Custom-radio-buttons](https://chakra-ui.com/docs/components/radio/usage#custom-radio-buttons) from  #1515  
The useRadio hook states that getCheckboxProps is deprecated.
In the [example](https://chakra-ui.com/docs/components/radio#custom-radio-buttons), the following code snippet:
```
function RadioCard(props) {
const { getInputProps, getCheckboxProps } = useRadio(props)
const input = getInputProps()
const checkbox = getCheckboxProps()
```
should be 
```
function RadioCard(props) {
const { getInputProps, getRadioProps } = useRadio(props)
const input = getInputProps()
const checkbox = getRadioProps()
```
```
function RadioCard(props) {
const { getInputProps, getRadioProps } = useRadio(props)
const input = getInputProps()
const checkbox = …
```

docs:updated useRadio snippets

---

layouts/changelog.tsx
pages/changelog/[version].tsx

Closes #1430  
>  Fix on changelog documentions not showing in algolia search
Currently search: results for changelog pages are not working, due to  to the path of the page being `/changelog/2.0.1 ` but the link in the search result is sending me to `/changelog/v2.0.1`. 
What I did is by prefixing the content path generated from content layer in getStaticPaths and updating the related anchor tags with prefix `v`
No
I am not very sure about the approach but please let me know if there any better way  I can improve on this

fix :search  results for changelog pages are not working, 

---

content/docs/hooks/use-disclosure.mdx

Closes #1540 
> When I am looking into the [parameter](https://chakra-ui.com/docs/hooks/use-disclosure#parameters) section of useDisclosure hook, I am not able to see any table for the parameters. This PR is about adding the parameters table.
> When I am looking into the [parameter](https://chakra-ui.com/docs/hooks/use-disclosure#parameters) section of useDisclosure hook, I am not able to see any table for the parameters.
>  The parameters table is added with `name`, `type` and their `description` 
> No
> N/A

docs(use-disclosure): add parameters table

---

content/docs/components/form-control/usage.mdx

I fixed the issue where a compile error was occurring because null was being specified for `htmlFor`.
The type of `htmlFor` is `﻿string | undefined`. Please refer to [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2317-L2320) for more information.
I removed htmlFor to prevent the compile error from occurring.
No
If it is preferred to explicitly specify `undefined`, please let me know.

fix(form-control): remove the htmlFor attribute

---

content/docs/components/popover/usage.mdx

Closes # 
Color of the `<PopoverArrow/>` does not match the color of the `<PopoverContent/>`
Arrow color does not match the popover background color
Arrow color does match the popover background color
No

Fix `<PopoverArrow/>` color on Popover example

---

pages/docs/components/index.tsx

Changes the word `prebuild` to `prebuilt` on the [components page](https://chakra-ui.com/docs/components).
I'm assuming this was a typo, but my apologies if I'm wrong 😄

docs: change "prebuild" to "prebuilt" for components page description

---

.all-sponsorsrc

Note that on the Open Collective side, https://opencollective.com/veepn-vpn the link to this app is https://veepn.com/vpn-apps/download-vpn-for-pc/ and the user requested us that this link be updated on the Chakra UI docs as well.

Update vpn-apps link to correct page

---

src/components/header.tsx

Increase nav bar z index to avoid it getting covered by popover
Closes # 
> Popover's z index is higher than the nav bar's, and it blocked the nav bar when it is opened.
>  Popover's z index is higher than the nav bar's, and it blocked the nav bar when it is opened.
> Nav bar has a higher z index now, it would not get blocked when popover is opened.
No

fix : increase nav bar z index

---

content/docs/components/drawer/usage.mdx

the doc's link to the wrong source files. I'm assuming its because the package is set to modal and not to drawer.
When clicking the doc link to the theme source of drawer it goes to modal.
When clicking the doc link to the theme source of drawer it goes to drawer.
no

Correct link for drawer docs

---

configs/search-meta.json
content/docs/styled-system/responsive-styles.mdx
content/docs/styled-system/theme.mdx

- Add `base` property to breakpoints object in `responsive-styles.mdx` and `theme.mdx`.
- In `responsive-styles.mdx` add links to breakpoints and theme object.
- Update comments in breakpoints objects stating that the pixel values are estimate and based on font size in default breakpoints that use `em` unit.
- Add link to learn more about `em` unit.
- Run `pnpm lint` which will change all single quotes to double quotes.
No

docs: update breakpoints object

---

configs/search-meta.json
content/docs/components/transitions/usage.mdx

Adds to the existing Collapse documentation. Adds the use of transition when trying to use motionProps on any elements using Collapse. The docs were not clear on what should I use to change the existing transition behavior.
I searched a long time on  how to change the animation of *AccordionPanel*. Must be easy, it accepts motionProps. Let's see whats it's using under the hood. Bam, found *Collapse*. Now *Collapse* is supposed to support all motionProps. But it doesn't. Or it does it in a way that is not useful to me (or any otheer user stuck on it).
> User can find the usage of transition to no longer be searching left and right.
[Link to original answer](https://github.com/chakra-ui/chakra-ui/issues/1017)

docs: add docs for usage of collapse

---

content/docs/styled-system/theme.mdx

bc spread operator, zIndices has a duplicated key
Remove duplicated key
No

Update theme.mdx zIndices

---

content/docs/styled-system/color-mode.mdx

Changes "Github" to "GitHub"
No

Fix typo in color-mode.mdx

---

configs/search-meta.json

Regenerate the search meta to includes links to the changelog for `v2.8.2` which is currently not present in prod when using the search bar.

refactor: regenerate search meta with v2.8.2 changelog

---

content/getting-started/nextjs-app-guide.mdx

In the "Next.js (App)" section, change `fonts.rubik.className` to `fonts.rubik.variable` so that it works as expected.
The current documentation uses `fonts.rubik.className` this makes the font apply to the entire site. This way, if we import more than one font, the entire website will be seen with the last imported font.
```html
<html lang='en' className={fonts.rubik.className}>
``` 
After merging this PR, the code example in the documentation will be fixed by changing to `fonts.rubik.variable`, this allows us to have control in `theme.ts` of the font that is used as shown in the documentation example.
```html
<html lang='en' className={fonts.rubik.variable}>
``` 
No.
This change is a minor fix to the documentation and does not affect the functionality of the Chakra UI. Ensures that the …

docs: Fix font usage in Next.js (App)

---

content/docs/components/input/usage.mdx

Update usage.mdx ([https://chakra-ui.com/docs/components/input](https://chakra-ui.com/docs/components/input)) to not use the children prop, but express the children as child node.
In the examples, some string children are defined through a prop.
In this proposal, the string children are passed as child nodes in the dom tree for improved clarity, instead of being passed as a prop.
No.
[https://chakra-ui.com/docs/components/input](https://chakra-ui.com/docs/components/input)

Update Input Component docs to not pass children as props, but as nodes

---

content/docs/components/slider/usage.mdx

Remove unnecessary line of code from `slider` documentation
We have a working slider, but it contains a line that does not affect its operation and is unnecessary
We have a working slider without unnecessary code
No

docs: Remove unnecessary line of code

---

content/docs/components/toast/usage.mdx

Resolves confusion found in #7547
Currently, the docs don't accurately describe how to use `ToastContainer`: it sounds like you need to include `ToastContainer` in order to create toasts from outside React, but really, you only need to include it to create toasts outside of `ChakraProvider`.
Docs for `createStandaloneToast` are incomplete.
Updated the wording of the `createStandaloneToast` docs.
No

docs(Toast): Clarified when to use ToastContainer with createStandaloneToast
